// Code generated by nuzur go-code-gen. DO NOT EDIT.

package claim

import (
	"context"

	"github.com/mklfarha/metiche/backend/core/module/claim/types"
	metichedb "github.com/mklfarha/metiche/backend/core/repository/gen"

	"github.com/gofrs/uuid"

	"time"

	"github.com/mklfarha/metiche/backend/entity/mapper"
)

func (m *module) Insert(
	ctx context.Context,
	req types.UpsertRequest,
	opts ...Option,
) (types.UpsertResponse, error) {

	// auto-generate primary-key UUIDs for new records when not supplied by the caller
	if req.Claim.ID == uuid.Nil {
		req.Claim.ID = uuid.Must(uuid.NewV4())
	}

	// server-managed timestamps (generated created_at/updated_at)
	req.Claim.CreatedAt = time.Now()
	req.Claim.UpdatedAt = time.Now()

	// validate the new record against the schema's field type/type-config rules
	if err := req.Claim.Validate(); err != nil {

		return types.UpsertResponse{}, err
	}

	optConfig := applyAllOptions(opts)

	tx := optConfig.SQLTx
	createdTx := false
	if tx == nil {
		ntx, err := m.repository.DB.Begin()
		if err != nil {
			return types.UpsertResponse{}, err
		}
		tx = ntx
		defer tx.Rollback()
		createdTx = true
	}

	qtx := m.repository.Queries.WithTx(tx)
	params := mapUpsertRequestToInsertParams(req)

	_, err := qtx.InsertClaim(
		ctx,
		params,
	)
	if err != nil {

		return types.UpsertResponse{}, err
	}

	if createdTx {
		err := tx.Commit()
		if err != nil {

			return types.UpsertResponse{}, err
		}
	}

	// The rows this module caches have changed, so everything it holds is
	// suspect: drop it rather than answer a later read from a snapshot that
	// predates this write. The cache is per entity, so this discards only this
	// entity's reads. (It is a no-op while a caller-supplied transaction is
	// still open — those reads bypass the cache anyway.)
	m.cache.Flush()

	return buildInsertResponse(req), nil
}

func buildInsertResponse(req types.UpsertRequest) types.UpsertResponse {
	return types.UpsertResponse{

		ID: req.Claim.ID,
	}
}

func mapUpsertRequestToInsertParams(req types.UpsertRequest) metichedb.InsertClaimParams {
	return metichedb.InsertClaimParams{
		ID: req.Claim.ID.String(),

		TeamUUID: req.Claim.TeamUUID.String(),

		ProjectUUID: req.Claim.ProjectUUID.String(),

		SessionUUID: req.Claim.SessionUUID.String(),

		MemberUUID: req.Claim.MemberUUID.String(),

		IntentUUID: mapper.UUIDPtrToNullString(req.Claim.IntentUUID),

		Key: req.Claim.Key,

		Mode: req.Claim.Mode.ToInt64(),

		Status: req.Claim.Status.ToInt64(),

		TtlSeconds: req.Claim.TtlSeconds,

		ExpiresAt: req.Claim.ExpiresAt,

		HardExpiresAt: req.Claim.HardExpiresAt,

		BreadthScore: req.Claim.BreadthScore,

		ReleasedAt: req.Claim.ReleasedAt,

		ReleaseReason: req.Claim.ReleaseReason,

		CreatedAt: req.Claim.CreatedAt,

		UpdatedAt: req.Claim.UpdatedAt,
	}
}
