// Code generated by nuzur go-code-gen. DO NOT EDIT.

package claim

import (
	"context"
	"errors"

	"github.com/mklfarha/metiche/backend/core/module/claim/types"
	metichedb "github.com/mklfarha/metiche/backend/core/repository/gen"

	"time"

	"github.com/mklfarha/metiche/backend/entity/mapper"
)

func (m *module) Update(
	ctx context.Context,
	req types.UpsertRequest,
	opts ...Option,
) (types.UpsertResponse, error) {
	optConfig := applyAllOptions(opts)

	tx := optConfig.SQLTx
	createdTx := false
	if tx == nil {
		ntx, err := m.repository.DB.Begin()
		if err != nil {
			return types.UpsertResponse{}, err
		}
		tx = ntx
		defer tx.Rollback()
		createdTx = true
	}

	qtx := m.repository.Queries.WithTx(tx)
	existing, err := qtx.FetchClaimByIDForUpdate(ctx,
		req.Claim.ID.String(),
	)
	if err != nil {

		return types.UpsertResponse{}, err
	}

	if len(existing) == 0 {
		err := errors.New("entity not found")

		return types.UpsertResponse{}, err
	}

	// refresh server-managed timestamps that update on every write (updated_at)
	req.Claim.UpdatedAt = time.Now()

	// validate the merged entity against the schema's field type/type-config rules
	if err := req.Claim.Validate(); err != nil {

		return types.UpsertResponse{}, err
	}

	params := mapUpsertRequestToUpdateParams(req)
	err = qtx.UpdateClaim(
		ctx,
		params,
	)
	if err != nil {

		return types.UpsertResponse{}, err
	}

	if createdTx {
		err := tx.Commit()
		if err != nil {

			return types.UpsertResponse{}, err
		}
	}

	// The rows this module caches have changed, so everything it holds is
	// suspect: drop it rather than answer a later read from a snapshot that
	// predates this write. The cache is per entity, so this discards only this
	// entity's reads. (It is a no-op while a caller-supplied transaction is
	// still open — those reads bypass the cache anyway.)
	m.cache.Flush()

	return buildUpdateResponse(req), nil
}

func buildUpdateResponse(req types.UpsertRequest) types.UpsertResponse {
	return types.UpsertResponse{

		ID: req.Claim.ID,
	}
}

func mapUpsertRequestToUpdateParams(req types.UpsertRequest) metichedb.UpdateClaimParams {
	return metichedb.UpdateClaimParams{
		ID: req.Claim.ID.String(),

		TeamUUID: req.Claim.TeamUUID.String(),

		ProjectUUID: req.Claim.ProjectUUID.String(),

		SessionUUID: req.Claim.SessionUUID.String(),

		MemberUUID: req.Claim.MemberUUID.String(),

		IntentUUID: mapper.UUIDPtrToNullString(req.Claim.IntentUUID),

		Key: req.Claim.Key,

		Mode: req.Claim.Mode.ToInt64(),

		Status: req.Claim.Status.ToInt64(),

		TtlSeconds: req.Claim.TtlSeconds,

		ExpiresAt: req.Claim.ExpiresAt,

		HardExpiresAt: req.Claim.HardExpiresAt,

		BreadthScore: req.Claim.BreadthScore,

		ReleasedAt: req.Claim.ReleasedAt,

		ReleaseReason: req.Claim.ReleaseReason,

		CreatedAt: req.Claim.CreatedAt,

		UpdatedAt: req.Claim.UpdatedAt,
	}
}
