// Code generated by nuzur go-code-gen. DO NOT EDIT.

package team_event

import (
	"encoding/json"
	"log"

	"github.com/gofrs/uuid"
	"github.com/guregu/null/v6"
	"github.com/mklfarha/metiche/backend/entity/event_payload"
	"github.com/mklfarha/metiche/backend/enums"
	"time"

	"github.com/mklfarha/metiche/backend/entity/mapper"
)

type TeamEvent struct {
	ID               uuid.UUID                  `json:"id"`
	TeamUUID         uuid.UUID                  `json:"team_uuid"`
	Sequence         int64                      `json:"sequence"`
	ProjectUUID      *uuid.UUID                 `json:"project_uuid"`
	SessionUUID      *uuid.UUID                 `json:"session_uuid"`
	AgentUUID        *uuid.UUID                 `json:"agent_uuid"`
	MemberUUID       *uuid.UUID                 `json:"member_uuid"`
	Kind             enums.EventKind            `json:"kind"`
	SubjectKind      enums.SubjectKind          `json:"subject_kind"`
	SubjectUUID      *uuid.UUID                 `json:"subject_uuid"`
	SubjectKey       null.String                `json:"subject_key"`
	Structural       bool                       `json:"structural"`
	Summary          null.String                `json:"summary"`
	Payload          event_payload.EventPayload `json:"payload"`
	IdempotencyKey   string                     `json:"idempotency_key"`
	ResponseSnapshot json.RawMessage            `json:"response_snapshot,omitempty"`
	OccurredAt       time.Time                  `json:"occurred_at"`
	CreatedAt        time.Time                  `json:"created_at"`
	UpdatedAt        time.Time                  `json:"updated_at"`
}

func (e TeamEvent) String() string {
	res, _ := json.Marshal(e)
	return string(res)
}

func (e TeamEvent) PrimaryKeyValues() []string {
	return []string{
		e.ID.String(),
	}
}

// The parameter is a plain []byte rather than json.RawMessage so that both a
// json.RawMessage and the mapper.JSON a repository model holds can be passed
// without a conversion at the call site.
func TeamEventFromJSON(data []byte) TeamEvent {
	entity := TeamEvent{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		if err2 := mapper.FlexibleUnmarshal(data, &entity); err2 != nil {
			log.Printf("flexible unmarshal error TeamEventFromJSON: %v\n", err2)
		}
	}
	return entity
}

func TeamEventSliceFromJSON(data []byte) []TeamEvent {
	entity := []TeamEvent{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		entity = []TeamEvent{}
		var rawSlice []json.RawMessage
		if err2 := json.Unmarshal(data, &rawSlice); err2 == nil {
			for _, raw := range rawSlice {
				item := TeamEvent{}
				if err3 := mapper.FlexibleUnmarshal(raw, &item); err3 != nil {
					log.Printf("flexible unmarshal error TeamEventSliceFromJSON item: %v\n", err3)
				}
				entity = append(entity, item)
			}
		}
	}
	return entity
}

func (e TeamEvent) ToJSON() json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error TeamEventToJSON: %v\n", err)
		return json.RawMessage("null")
	}
	return res
}

func TeamEventToJSON(e TeamEvent) json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error TeamEventToJSON: %v\n", err)
		return json.RawMessage("null")
	}
	return res
}

// TeamEventSliceToJSON serializes a ONE_TO_MANY embed for its JSON column.
// An absent embed is the EMPTY ARRAY, never a zero-length json.RawMessage: a
// zero-length value reaches the driver as the empty string, which is not valid
// JSON, so a create that simply omitted an optional array embed was rejected by
// the database ("invalid input syntax for type json", MySQL error 3140) and
// surfaced as a 500. "[]" is also exactly what an explicit `"field": []` stores,
// so the omitted and the explicitly-empty request round-trip to the same value.
func TeamEventSliceToJSON(e []TeamEvent) json.RawMessage {
	if e == nil {
		return json.RawMessage("[]")
	}
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error TeamEventSliceToJSON: %v\n", err)
		return json.RawMessage("[]")
	}
	return res
}
