// Code generated by nuzur go-code-gen. DO NOT EDIT.

package decision_path

import (
	"context"

	"github.com/mklfarha/metiche/backend/core/module/decision_path/types"
	metichedb "github.com/mklfarha/metiche/backend/core/repository/gen"

	"github.com/gofrs/uuid"

	"time"

	"github.com/mklfarha/metiche/backend/entity/mapper"
)

func (m *module) Insert(
	ctx context.Context,
	req types.UpsertRequest,
	opts ...Option,
) (types.UpsertResponse, error) {

	// auto-generate primary-key UUIDs for new records when not supplied by the caller
	if req.DecisionPath.ID == uuid.Nil {
		req.DecisionPath.ID = uuid.Must(uuid.NewV4())
	}

	// server-managed timestamps (generated created_at/updated_at)
	req.DecisionPath.CreatedAt = time.Now()
	req.DecisionPath.UpdatedAt = time.Now()

	// validate the new record against the schema's field type/type-config rules
	if err := req.DecisionPath.Validate(); err != nil {

		return types.UpsertResponse{}, err
	}

	optConfig := applyAllOptions(opts)

	tx := optConfig.SQLTx
	createdTx := false
	if tx == nil {
		ntx, err := m.repository.DB.Begin()
		if err != nil {
			return types.UpsertResponse{}, err
		}
		tx = ntx
		defer tx.Rollback()
		createdTx = true
	}

	qtx := m.repository.Queries.WithTx(tx)
	params := mapUpsertRequestToInsertParams(req)

	_, err := qtx.InsertDecisionPath(
		ctx,
		params,
	)
	if err != nil {

		return types.UpsertResponse{}, err
	}

	if createdTx {
		err := tx.Commit()
		if err != nil {

			return types.UpsertResponse{}, err
		}
	}

	// The rows this module caches have changed, so everything it holds is
	// suspect: drop it rather than answer a later read from a snapshot that
	// predates this write. The cache is per entity, so this discards only this
	// entity's reads. (It is a no-op while a caller-supplied transaction is
	// still open — those reads bypass the cache anyway.)
	m.cache.Flush()

	return buildInsertResponse(req), nil
}

func buildInsertResponse(req types.UpsertRequest) types.UpsertResponse {
	return types.UpsertResponse{

		ID: req.DecisionPath.ID,
	}
}

func mapUpsertRequestToInsertParams(req types.UpsertRequest) metichedb.InsertDecisionPathParams {
	return metichedb.InsertDecisionPathParams{
		ID: req.DecisionPath.ID.String(),

		DecisionUUID: req.DecisionPath.DecisionUUID.String(),

		TeamUUID: req.DecisionPath.TeamUUID.String(),

		ProjectUUID: mapper.UUIDPtrToNullString(req.DecisionPath.ProjectUUID),

		Pattern: req.DecisionPath.Pattern,

		PatternNorm: req.DecisionPath.PatternNorm,

		Kind: req.DecisionPath.Kind.ToInt64(),

		Prefix: req.DecisionPath.Prefix,

		Depth: req.DecisionPath.Depth,

		CreatedAt: req.DecisionPath.CreatedAt,

		UpdatedAt: req.DecisionPath.UpdatedAt,
	}
}
