// Code generated by nuzur go-code-gen. DO NOT EDIT.

package browser_session

import (
	"context"
	"fmt"

	"github.com/mklfarha/metiche/backend/core/module/browser_session/types"

	"errors"
	metichedb "github.com/mklfarha/metiche/backend/core/repository/gen"
)

func (m *module) FetchBrowserSessionByAccountUUID(
	ctx context.Context,
	req types.FetchBrowserSessionByAccountUUIDRequest,
	opts ...Option,
) (types.FetchBrowserSessionByAccountUUIDResponse, error) {

	resolvedOpts := applyAllOptions(opts)
	queries := m.repository.Queries
	if resolvedOpts.SQLTx != nil {
		queries = queries.WithTx(resolvedOpts.SQLTx)
	}
	// A read inside a transaction must observe that transaction's own
	// uncommitted writes, so it can neither be served from the shared cache nor
	// be collapsed into another caller's in-flight query.
	skipShared := resolvedOpts.SkipCache || resolvedOpts.SQLTx != nil
	cacheKey := fmt.Sprintf("FetchBrowserSessionByAccountUUID:%v", req)
	if !skipShared {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.FetchBrowserSessionByAccountUUIDResponse), nil
		}
	}
	fetch := func() (any, error) {
		if req.OrderBy == "" {
			models, err := queries.FetchBrowserSessionByAccountUUID(
				ctx,
				metichedb.FetchBrowserSessionByAccountUUIDParams{
					AccountUUID: req.AccountUUID.String(),

					Offset: req.Offset,
					Limit:  req.Limit,
				},
			)

			if err != nil {

				return types.FetchBrowserSessionByAccountUUIDResponse{}, err
			}
			return types.FetchBrowserSessionByAccountUUIDResponse{
				Results: mapModelsToEntities(models),
			}, nil
		}

		timeFields := []string{
			"expires_at",
		}

		orderByFieldFound := false
		for _, tf := range timeFields {
			if tf == req.OrderBy {
				orderByFieldFound = true
				break
			}
		}

		if !orderByFieldFound {
			err := errors.New("order by field not found")

			return types.FetchBrowserSessionByAccountUUIDResponse{}, err
		}

		sort := "ASC"
		if req.Sort != "" {
			if req.Sort == "ASC" || req.Sort == "DESC" {
				sort = req.Sort
			} else {
				err := errors.New("invalid sort value only ASC or DESC are valid")

				return types.FetchBrowserSessionByAccountUUIDResponse{}, err
			}
		}

		switch req.OrderBy {

		case "expires_at":
			if sort == "ASC" {
				models, err := queries.FetchBrowserSessionByAccountUUIDOrderedByExpiresAtASC(
					ctx,
					metichedb.FetchBrowserSessionByAccountUUIDOrderedByExpiresAtASCParams{
						AccountUUID: req.AccountUUID.String(),

						Offset: req.Offset,
						Limit:  req.Limit,
					},
				)
				if err != nil {

					return types.FetchBrowserSessionByAccountUUIDResponse{}, err
				}
				return types.FetchBrowserSessionByAccountUUIDResponse{
					Results: mapModelsToEntities(models),
				}, nil
			} else {
				models, err := queries.FetchBrowserSessionByAccountUUIDOrderedByExpiresAtDESC(
					ctx,
					metichedb.FetchBrowserSessionByAccountUUIDOrderedByExpiresAtDESCParams{
						AccountUUID: req.AccountUUID.String(),

						Offset: req.Offset,
						Limit:  req.Limit,
					},
				)
				if err != nil {

					return types.FetchBrowserSessionByAccountUUIDResponse{}, err
				}
				return types.FetchBrowserSessionByAccountUUIDResponse{
					Results: mapModelsToEntities(models),
				}, nil
			}

		}

		err := errors.New("could not process request")

		return types.FetchBrowserSessionByAccountUUIDResponse{}, err
	} // end fetch
	var v any
	var fetchErr error
	if skipShared {
		v, fetchErr = fetch()
	} else {
		v, fetchErr, _ = m.sg.Do(cacheKey, fetch)
	}
	if fetchErr != nil {
		return types.FetchBrowserSessionByAccountUUIDResponse{}, fetchErr
	}
	result := v.(types.FetchBrowserSessionByAccountUUIDResponse)
	if !skipShared {
		m.cache.Set(cacheKey, result, 0)
	}
	return result, nil

}
