// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/mklfarha/metiche/backend/entity/team"

	"go.uber.org/zap/zapcore"
)

type FetchTeamByJoinCodeRequest struct {
	JoinCode string

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchTeamByJoinCodeRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	return nil
}

type FetchTeamByJoinCodeResponse struct {
	Results []main_entity.Team
}
