// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/mklfarha/metiche/backend/entity/team"

	"go.uber.org/zap/zapcore"
)

type FetchTeamBySlugRequest struct {
	Slug string

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchTeamBySlugRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	return nil
}

type FetchTeamBySlugResponse struct {
	Results []main_entity.Team
}
