// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/mklfarha/metiche/backend/entity/plan"

	"github.com/mklfarha/metiche/backend/enums"
	"go.uber.org/zap/zapcore"
)

type FetchPlanByIsInstanceDefaultAndStatusRequest struct {
	IsInstanceDefault bool
	Status            enums.RecordStatus

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchPlanByIsInstanceDefaultAndStatusRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	return nil
}

type FetchPlanByIsInstanceDefaultAndStatusResponse struct {
	Results []main_entity.Plan
}
