// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/mklfarha/metiche/backend/entity/browser_session"

	"go.uber.org/zap/zapcore"
)

type FetchBrowserSessionBySecretHashRequest struct {
	SecretHash string

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchBrowserSessionBySecretHashRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	return nil
}

type FetchBrowserSessionBySecretHashResponse struct {
	Results []main_entity.BrowserSession
}
