// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/mklfarha/metiche/backend/entity/contract_field"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchContractFieldByContractUUIDAndPathSnakeRequest struct {
	ContractUUID uuid.UUID
	PathSnake    string

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchContractFieldByContractUUIDAndPathSnakeRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("contract_uuid", r.ContractUUID.String())

	return nil
}

type FetchContractFieldByContractUUIDAndPathSnakeResponse struct {
	Results []main_entity.ContractField
}
