// Code generated by nuzur go-code-gen. DO NOT EDIT.

package repository

import (
	"context"

	"database/sql"

	metichedb "github.com/mklfarha/metiche/backend/core/repository/gen"
	"github.com/mklfarha/metiche/backend/core/repository/list"
)

type Implementation struct {
	Queries *metichedb.Queries
	DB      *sql.DB
	List    *list.Implementation
}

func New(db *sql.DB) *Implementation {
	queries := metichedb.New(db)
	return &Implementation{
		Queries: queries,
		DB:      db,
		List:    list.New(),
	}
}

// BuildListEntityQuery returns the query text and the arguments bound into it.
// The two must travel together: the text carries only placeholders now, so
// running it without the args is a "bind message supplies 0 parameters" error,
// not a query with the filter silently ignored.
func (i *Implementation) BuildListEntityQuery(ctx context.Context, request list.ListRequest, entity list.ListEntity, onlyCount bool) (string, []any, error) {
	return i.List.BuildListEntityQuery(ctx, request, entity, onlyCount)
}
