// Code generated by nuzur go-code-gen. DO NOT EDIT.

package notification_channel

import (
	"github.com/mklfarha/metiche/backend/entity/validation"
)

// Validate checks this NotificationChannel against the schema's field type and
// type-config rules, aggregating every problem into a single *validation.Error.
// It mirrors the change-request data validation enforced in
// product/module/datavalidation, so data written through this API is held to
// the same rules. Generated by go-code-gen — do not edit.
func (e NotificationChannel) Validate() error {
	c := validation.NewCollector()
	if e.ID.IsNil() {
		c.Require("notification_channel.id")
	}
	if e.TeamUUID.IsNil() {
		c.Require("notification_channel.team_uuid")
	}
	if e.Key == "" {
		c.Require("notification_channel.key")
	} else {
		c.Field("notification_channel.key", validation.String(e.Key, 0, 32, ""))

	}
	if e.Kind.ToInt64() == 0 {
		c.Require("notification_channel.kind")
	} else {
		c.Field("notification_channel.kind", validation.EnumMember(e.Kind.ToInt64(), []int64{0, 1, 2, 3}, "notification_channel_kind"))

	}
	if e.Label == "" {
		c.Require("notification_channel.label")
	} else {
		c.Field("notification_channel.label", validation.String(e.Label, 0, 120, ""))

	}
	if e.TargetURL == "" {
		c.Require("notification_channel.target_url")
	} else {
		c.Field("notification_channel.target_url", validation.String(e.TargetURL, 0, 512, ""))

	}
	if e.MinSeverity.ToInt64() == 0 {
		c.Require("notification_channel.min_severity")
	} else {
		c.Field("notification_channel.min_severity", validation.EnumMember(e.MinSeverity.ToInt64(), []int64{0, 1, 2, 3, 4}, "conflict_severity"))

	}
	if e.Status.ToInt64() == 0 {
		c.Require("notification_channel.status")
	} else {
		c.Field("notification_channel.status", validation.EnumMember(e.Status.ToInt64(), []int64{0, 1, 2}, "record_status"))

	}
	if e.DeliveryStatus.ToInt64() == 0 {
		c.Require("notification_channel.delivery_status")
	} else {
		c.Field("notification_channel.delivery_status", validation.EnumMember(e.DeliveryStatus.ToInt64(), []int64{0, 1, 2, 3, 4}, "delivery_status"))

	}
	c.Field("notification_channel.consecutive_failures", validation.Integer(e.ConsecutiveFailures, false, 0, 0, false, false, false, true, -32768, 32767))
	if e.LastError.Valid && e.LastError.String != "" {
		c.Field("notification_channel.last_error", validation.String(e.LastError.String, 0, 400, ""))

	}

	return c.Result()
}
