// Code generated by nuzur go-code-gen. DO NOT EDIT.

package instruction

import (
	"context"

	"github.com/mklfarha/metiche/backend/core/module/instruction/types"
	metichedb "github.com/mklfarha/metiche/backend/core/repository/gen"

	"github.com/gofrs/uuid"

	"time"

	"github.com/mklfarha/metiche/backend/entity/mapper"
)

func (m *module) Insert(
	ctx context.Context,
	req types.UpsertRequest,
	opts ...Option,
) (types.UpsertResponse, error) {

	// auto-generate primary-key UUIDs for new records when not supplied by the caller
	if req.Instruction.ID == uuid.Nil {
		req.Instruction.ID = uuid.Must(uuid.NewV4())
	}

	// server-managed timestamps (generated created_at/updated_at)
	req.Instruction.CreatedAt = time.Now()
	req.Instruction.UpdatedAt = time.Now()

	// validate the new record against the schema's field type/type-config rules
	if err := req.Instruction.Validate(); err != nil {

		return types.UpsertResponse{}, err
	}

	optConfig := applyAllOptions(opts)

	tx := optConfig.SQLTx
	createdTx := false
	if tx == nil {
		ntx, err := m.repository.DB.Begin()
		if err != nil {
			return types.UpsertResponse{}, err
		}
		tx = ntx
		defer tx.Rollback()
		createdTx = true
	}

	qtx := m.repository.Queries.WithTx(tx)
	params := mapUpsertRequestToInsertParams(req)

	_, err := qtx.InsertInstruction(
		ctx,
		params,
	)
	if err != nil {

		return types.UpsertResponse{}, err
	}

	if createdTx {
		err := tx.Commit()
		if err != nil {

			return types.UpsertResponse{}, err
		}
	}

	// The rows this module caches have changed, so everything it holds is
	// suspect: drop it rather than answer a later read from a snapshot that
	// predates this write. The cache is per entity, so this discards only this
	// entity's reads. (It is a no-op while a caller-supplied transaction is
	// still open — those reads bypass the cache anyway.)
	m.cache.Flush()

	return buildInsertResponse(req), nil
}

func buildInsertResponse(req types.UpsertRequest) types.UpsertResponse {
	return types.UpsertResponse{

		ID: req.Instruction.ID,
	}
}

func mapUpsertRequestToInsertParams(req types.UpsertRequest) metichedb.InsertInstructionParams {
	return metichedb.InsertInstructionParams{
		ID: req.Instruction.ID.String(),

		TeamUUID: req.Instruction.TeamUUID.String(),

		TargetSessionUUID: mapper.UUIDPtrToNullString(req.Instruction.TargetSessionUUID),

		TargetAgentUUID: mapper.UUIDPtrToNullString(req.Instruction.TargetAgentUUID),

		Key: req.Instruction.Key,

		Source: req.Instruction.Source.ToInt64(),

		Kind: req.Instruction.Kind.ToInt64(),

		Body: req.Instruction.Body,

		RefKind: req.Instruction.RefKind.ToNullInt(),

		RefUUID: mapper.UUIDPtrToNullString(req.Instruction.RefUUID),

		RequiresReport: req.Instruction.RequiresReport,

		Status: req.Instruction.Status.ToInt64(),

		RaisedByMemberUUID: mapper.UUIDPtrToNullString(req.Instruction.RaisedByMemberUUID),

		DeliveredAt: req.Instruction.DeliveredAt,

		ActedAt: req.Instruction.ActedAt,

		Action: req.Instruction.Action.ToNullInt(),

		ActionNote: req.Instruction.ActionNote,

		ExpiresAt: req.Instruction.ExpiresAt,

		CreatedAt: req.Instruction.CreatedAt,

		UpdatedAt: req.Instruction.UpdatedAt,

		TargetMemberUUID: mapper.UUIDPtrToNullString(req.Instruction.TargetMemberUUID),
	}
}
