// Code generated by nuzur go-code-gen. DO NOT EDIT.

package claim

import (
	entitytypes "github.com/mklfarha/metiche/backend/entity/types"
)

func (e Claim) FieldIdentifierToTypeMap() map[string]entitytypes.FieldType {
	return map[string]entitytypes.FieldType{
		"id":              entitytypes.StringFieldType,
		"team_uuid":       entitytypes.StringFieldType,
		"project_uuid":    entitytypes.StringFieldType,
		"session_uuid":    entitytypes.StringFieldType,
		"member_uuid":     entitytypes.StringFieldType,
		"intent_uuid":     entitytypes.StringFieldType,
		"key":             entitytypes.StringFieldType,
		"mode":            entitytypes.SingleEnumFieldType,
		"status":          entitytypes.SingleEnumFieldType,
		"ttl_seconds":     entitytypes.IntFieldType,
		"expires_at":      entitytypes.TimestampFieldType,
		"hard_expires_at": entitytypes.TimestampFieldType,
		"breadth_score":   entitytypes.IntFieldType,
		"released_at":     entitytypes.TimestampFieldType,
		"release_reason":  entitytypes.StringFieldType,
		"created_at":      entitytypes.TimestampFieldType,
		"updated_at":      entitytypes.TimestampFieldType,
	}
}

func (e Claim) OrderedFieldIdentifiers() []string {
	res := []string{}
	res = append(res, "id")
	res = append(res, "team_uuid")
	res = append(res, "project_uuid")
	res = append(res, "session_uuid")
	res = append(res, "member_uuid")
	res = append(res, "intent_uuid")
	res = append(res, "key")
	res = append(res, "mode")
	res = append(res, "status")
	res = append(res, "ttl_seconds")
	res = append(res, "expires_at")
	res = append(res, "hard_expires_at")
	res = append(res, "breadth_score")
	res = append(res, "released_at")
	res = append(res, "release_reason")
	res = append(res, "created_at")
	res = append(res, "updated_at")

	return res
}

func (e Claim) DependantFieldIdentifierToTypeMap() map[string]map[string]entitytypes.FieldType {
	res := make(map[string]map[string]entitytypes.FieldType)

	return res
}

func (e Claim) EntityIdentifier() string {
	return "claim"
}

func (e Claim) PrimaryKeyIdentifiers() []string {
	return []string{
		"id",
	}
}

func (e Claim) ArrayFieldIdentifierToType() map[string]entitytypes.FieldType {
	res := make(map[string]entitytypes.FieldType)

	return res
}
