// Code generated by nuzur go-code-gen. DO NOT EDIT.

package claim

import (
	"encoding/json"
	"log"

	"github.com/gofrs/uuid"
	"github.com/guregu/null/v6"
	"github.com/mklfarha/metiche/backend/enums"
	"time"

	"github.com/mklfarha/metiche/backend/entity/mapper"
)

type Claim struct {
	ID            uuid.UUID         `json:"id"`
	TeamUUID      uuid.UUID         `json:"team_uuid"`
	ProjectUUID   uuid.UUID         `json:"project_uuid"`
	SessionUUID   uuid.UUID         `json:"session_uuid"`
	MemberUUID    uuid.UUID         `json:"member_uuid"`
	IntentUUID    *uuid.UUID        `json:"intent_uuid"`
	Key           string            `json:"key"`
	Mode          enums.ClaimMode   `json:"mode"`
	Status        enums.ClaimStatus `json:"status"`
	TtlSeconds    int64             `json:"ttl_seconds"`
	ExpiresAt     time.Time         `json:"expires_at"`
	HardExpiresAt time.Time         `json:"hard_expires_at"`
	BreadthScore  int64             `json:"breadth_score"`
	ReleasedAt    null.Time         `json:"released_at"`
	ReleaseReason null.String       `json:"release_reason"`
	CreatedAt     time.Time         `json:"created_at"`
	UpdatedAt     time.Time         `json:"updated_at"`
}

func (e Claim) String() string {
	res, _ := json.Marshal(e)
	return string(res)
}

func (e Claim) PrimaryKeyValues() []string {
	return []string{
		e.ID.String(),
	}
}

// The parameter is a plain []byte rather than json.RawMessage so that both a
// json.RawMessage and the mapper.JSON a repository model holds can be passed
// without a conversion at the call site.
func ClaimFromJSON(data []byte) Claim {
	entity := Claim{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		if err2 := mapper.FlexibleUnmarshal(data, &entity); err2 != nil {
			log.Printf("flexible unmarshal error ClaimFromJSON: %v\n", err2)
		}
	}
	return entity
}

func ClaimSliceFromJSON(data []byte) []Claim {
	entity := []Claim{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		entity = []Claim{}
		var rawSlice []json.RawMessage
		if err2 := json.Unmarshal(data, &rawSlice); err2 == nil {
			for _, raw := range rawSlice {
				item := Claim{}
				if err3 := mapper.FlexibleUnmarshal(raw, &item); err3 != nil {
					log.Printf("flexible unmarshal error ClaimSliceFromJSON item: %v\n", err3)
				}
				entity = append(entity, item)
			}
		}
	}
	return entity
}

func (e Claim) ToJSON() json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error ClaimToJSON: %v\n", err)
		return json.RawMessage("null")
	}
	return res
}

func ClaimToJSON(e Claim) json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error ClaimToJSON: %v\n", err)
		return json.RawMessage("null")
	}
	return res
}

// ClaimSliceToJSON serializes a ONE_TO_MANY embed for its JSON column.
// An absent embed is the EMPTY ARRAY, never a zero-length json.RawMessage: a
// zero-length value reaches the driver as the empty string, which is not valid
// JSON, so a create that simply omitted an optional array embed was rejected by
// the database ("invalid input syntax for type json", MySQL error 3140) and
// surfaced as a 500. "[]" is also exactly what an explicit `"field": []` stores,
// so the omitted and the explicitly-empty request round-trip to the same value.
func ClaimSliceToJSON(e []Claim) json.RawMessage {
	if e == nil {
		return json.RawMessage("[]")
	}
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error ClaimSliceToJSON: %v\n", err)
		return json.RawMessage("[]")
	}
	return res
}
