// Code generated by nuzur go-code-gen. DO NOT EDIT.

package intent

import (
	"encoding/json"
	"log"

	"github.com/gofrs/uuid"
	"github.com/guregu/null/v6"
	"github.com/mklfarha/metiche/backend/enums"
	"time"

	"github.com/mklfarha/metiche/backend/entity/mapper"
)

type Intent struct {
	ID          uuid.UUID          `json:"id"`
	TeamUUID    uuid.UUID          `json:"team_uuid"`
	ProjectUUID uuid.UUID          `json:"project_uuid"`
	SessionUUID uuid.UUID          `json:"session_uuid"`
	MemberUUID  uuid.UUID          `json:"member_uuid"`
	Key         string             `json:"key"`
	Summary     string             `json:"summary"`
	Detail      null.String        `json:"detail"`
	Kind        enums.IntentKind   `json:"kind"`
	Status      enums.IntentStatus `json:"status"`
	ExternalRef null.String        `json:"external_ref"`
	Revision    int64              `json:"revision"`
	DeclaredAt  null.Time          `json:"declared_at"`
	StartedAt   null.Time          `json:"started_at"`
	EndedAt     null.Time          `json:"ended_at"`
	ExpiresAt   null.Time          `json:"expires_at"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

func (e Intent) String() string {
	res, _ := json.Marshal(e)
	return string(res)
}

func (e Intent) PrimaryKeyValues() []string {
	return []string{
		e.ID.String(),
	}
}

// The parameter is a plain []byte rather than json.RawMessage so that both a
// json.RawMessage and the mapper.JSON a repository model holds can be passed
// without a conversion at the call site.
func IntentFromJSON(data []byte) Intent {
	entity := Intent{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		if err2 := mapper.FlexibleUnmarshal(data, &entity); err2 != nil {
			log.Printf("flexible unmarshal error IntentFromJSON: %v\n", err2)
		}
	}
	return entity
}

func IntentSliceFromJSON(data []byte) []Intent {
	entity := []Intent{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		entity = []Intent{}
		var rawSlice []json.RawMessage
		if err2 := json.Unmarshal(data, &rawSlice); err2 == nil {
			for _, raw := range rawSlice {
				item := Intent{}
				if err3 := mapper.FlexibleUnmarshal(raw, &item); err3 != nil {
					log.Printf("flexible unmarshal error IntentSliceFromJSON item: %v\n", err3)
				}
				entity = append(entity, item)
			}
		}
	}
	return entity
}

func (e Intent) ToJSON() json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error IntentToJSON: %v\n", err)
		return json.RawMessage("null")
	}
	return res
}

func IntentToJSON(e Intent) json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error IntentToJSON: %v\n", err)
		return json.RawMessage("null")
	}
	return res
}

// IntentSliceToJSON serializes a ONE_TO_MANY embed for its JSON column.
// An absent embed is the EMPTY ARRAY, never a zero-length json.RawMessage: a
// zero-length value reaches the driver as the empty string, which is not valid
// JSON, so a create that simply omitted an optional array embed was rejected by
// the database ("invalid input syntax for type json", MySQL error 3140) and
// surfaced as a 500. "[]" is also exactly what an explicit `"field": []` stores,
// so the omitted and the explicitly-empty request round-trip to the same value.
func IntentSliceToJSON(e []Intent) json.RawMessage {
	if e == nil {
		return json.RawMessage("[]")
	}
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error IntentSliceToJSON: %v\n", err)
		return json.RawMessage("[]")
	}
	return res
}
