// Code generated by nuzur go-code-gen. DO NOT EDIT.

package account

import (
	"context"
	"errors"

	"github.com/mklfarha/metiche/backend/core/module/account/types"
	metichedb "github.com/mklfarha/metiche/backend/core/repository/gen"

	"time"
)

func (m *module) Update(
	ctx context.Context,
	req types.UpsertRequest,
	opts ...Option,
) (types.UpsertResponse, error) {
	optConfig := applyAllOptions(opts)

	tx := optConfig.SQLTx
	createdTx := false
	if tx == nil {
		ntx, err := m.repository.DB.Begin()
		if err != nil {
			return types.UpsertResponse{}, err
		}
		tx = ntx
		defer tx.Rollback()
		createdTx = true
	}

	qtx := m.repository.Queries.WithTx(tx)
	existing, err := qtx.FetchAccountByIDForUpdate(ctx,
		req.Account.ID.String(),
	)
	if err != nil {

		return types.UpsertResponse{}, err
	}

	if len(existing) == 0 {
		err := errors.New("entity not found")

		return types.UpsertResponse{}, err
	}

	// refresh server-managed timestamps that update on every write (updated_at)
	req.Account.UpdatedAt = time.Now()

	// validate the merged entity against the schema's field type/type-config rules
	if err := req.Account.Validate(); err != nil {

		return types.UpsertResponse{}, err
	}

	params := mapUpsertRequestToUpdateParams(req)
	err = qtx.UpdateAccount(
		ctx,
		params,
	)
	if err != nil {

		return types.UpsertResponse{}, err
	}

	if createdTx {
		err := tx.Commit()
		if err != nil {

			return types.UpsertResponse{}, err
		}
	}

	// The rows this module caches have changed, so everything it holds is
	// suspect: drop it rather than answer a later read from a snapshot that
	// predates this write. The cache is per entity, so this discards only this
	// entity's reads. (It is a no-op while a caller-supplied transaction is
	// still open — those reads bypass the cache anyway.)
	m.cache.Flush()

	return buildUpdateResponse(req), nil
}

func buildUpdateResponse(req types.UpsertRequest) types.UpsertResponse {
	return types.UpsertResponse{

		ID: req.Account.ID,
	}
}

func mapUpsertRequestToUpdateParams(req types.UpsertRequest) metichedb.UpdateAccountParams {
	return metichedb.UpdateAccountParams{
		ID: req.Account.ID.String(),

		Key: req.Account.Key,

		DisplayName: req.Account.DisplayName,

		TokenHash: req.Account.TokenHash,

		IdentityProvider: req.Account.IdentityProvider.ToInt64(),

		IdentitySubject: req.Account.IdentitySubject,

		IdentityHandle: req.Account.IdentityHandle,

		Email: req.Account.Email,

		ClaimedAt: req.Account.ClaimedAt,

		Status: req.Account.Status.ToInt64(),

		LastSeenAt: req.Account.LastSeenAt,

		CreatedAt: req.Account.CreatedAt,

		UpdatedAt: req.Account.UpdatedAt,
	}
}
