// Code generated by nuzur go-code-gen. DO NOT EDIT.

package limit_event

import (
	"context"
	"fmt"

	"github.com/mklfarha/metiche/backend/core/module/limit_event/types"

	"errors"
	metichedb "github.com/mklfarha/metiche/backend/core/repository/gen"
)

func (m *module) FetchLimitEventByTeamUUIDAndDimension(
	ctx context.Context,
	req types.FetchLimitEventByTeamUUIDAndDimensionRequest,
	opts ...Option,
) (types.FetchLimitEventByTeamUUIDAndDimensionResponse, error) {

	resolvedOpts := applyAllOptions(opts)
	queries := m.repository.Queries
	if resolvedOpts.SQLTx != nil {
		queries = queries.WithTx(resolvedOpts.SQLTx)
	}
	// A read inside a transaction must observe that transaction's own
	// uncommitted writes, so it can neither be served from the shared cache nor
	// be collapsed into another caller's in-flight query.
	skipShared := resolvedOpts.SkipCache || resolvedOpts.SQLTx != nil
	cacheKey := fmt.Sprintf("FetchLimitEventByTeamUUIDAndDimension:%v", req)
	if !skipShared {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.FetchLimitEventByTeamUUIDAndDimensionResponse), nil
		}
	}
	fetch := func() (any, error) {
		if req.OrderBy == "" {
			models, err := queries.FetchLimitEventByTeamUUIDAndDimension(
				ctx,
				metichedb.FetchLimitEventByTeamUUIDAndDimensionParams{
					TeamUUID: req.TeamUUID.String(),

					Dimension: req.Dimension,

					Offset: req.Offset,
					Limit:  req.Limit,
				},
			)

			if err != nil {

				return types.FetchLimitEventByTeamUUIDAndDimensionResponse{}, err
			}
			return types.FetchLimitEventByTeamUUIDAndDimensionResponse{
				Results: mapModelsToEntities(models),
			}, nil
		}

		err := errors.New("could not process request")

		return types.FetchLimitEventByTeamUUIDAndDimensionResponse{}, err
	} // end fetch
	var v any
	var fetchErr error
	if skipShared {
		v, fetchErr = fetch()
	} else {
		v, fetchErr, _ = m.sg.Do(cacheKey, fetch)
	}
	if fetchErr != nil {
		return types.FetchLimitEventByTeamUUIDAndDimensionResponse{}, fetchErr
	}
	result := v.(types.FetchLimitEventByTeamUUIDAndDimensionResponse)
	if !skipShared {
		m.cache.Set(cacheKey, result, 0)
	}
	return result, nil

}
