// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/mklfarha/metiche/backend/entity/limit_event"

	"github.com/gofrs/uuid"
)

type UpsertRequest struct {
	LimitEvent main_entity.LimitEvent
}

type UpsertResponse struct {
	ID uuid.UUID
}
