// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/mklfarha/metiche/backend/entity/session"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchSessionByTeamUUIDAndKeyRequest struct {
	TeamUUID uuid.UUID
	Key      string

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchSessionByTeamUUIDAndKeyRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("team_uuid", r.TeamUUID.String())

	return nil
}

type FetchSessionByTeamUUIDAndKeyResponse struct {
	Results []main_entity.Session
}
