// Code generated by nuzur go-code-gen. DO NOT EDIT.

package intent_token

import (
	entitytypes "github.com/mklfarha/metiche/backend/entity/types"
)

func (e IntentToken) FieldIdentifierToTypeMap() map[string]entitytypes.FieldType {
	return map[string]entitytypes.FieldType{
		"id":           entitytypes.StringFieldType,
		"intent_uuid":  entitytypes.StringFieldType,
		"team_uuid":    entitytypes.StringFieldType,
		"project_uuid": entitytypes.StringFieldType,
		"token":        entitytypes.StringFieldType,
		"weight":       entitytypes.IntFieldType,
		"created_at":   entitytypes.TimestampFieldType,
		"updated_at":   entitytypes.TimestampFieldType,
	}
}

func (e IntentToken) OrderedFieldIdentifiers() []string {
	res := []string{}
	res = append(res, "id")
	res = append(res, "intent_uuid")
	res = append(res, "team_uuid")
	res = append(res, "project_uuid")
	res = append(res, "token")
	res = append(res, "weight")
	res = append(res, "created_at")
	res = append(res, "updated_at")

	return res
}

func (e IntentToken) DependantFieldIdentifierToTypeMap() map[string]map[string]entitytypes.FieldType {
	res := make(map[string]map[string]entitytypes.FieldType)

	return res
}

func (e IntentToken) EntityIdentifier() string {
	return "intent_token"
}

func (e IntentToken) PrimaryKeyIdentifiers() []string {
	return []string{
		"id",
	}
}

func (e IntentToken) ArrayFieldIdentifierToType() map[string]entitytypes.FieldType {
	res := make(map[string]entitytypes.FieldType)

	return res
}
