// Code generated by nuzur go-code-gen. DO NOT EDIT.

package event_payload

import (
	"encoding/json"
	"log"

	"github.com/gofrs/uuid"
	"github.com/guregu/null/v6"
	"github.com/mklfarha/metiche/backend/enums"

	"github.com/mklfarha/metiche/backend/entity/mapper"
)

type EventPayload struct {
	Message         null.String            `json:"message"`
	PreviousStatus  null.String            `json:"previous_status"`
	NewStatus       null.String            `json:"new_status"`
	Severity        enums.ConflictSeverity `json:"severity"`
	ConflictUUID    *uuid.UUID             `json:"conflict_uuid"`
	IntentUUID      *uuid.UUID             `json:"intent_uuid"`
	ClaimUUID       *uuid.UUID             `json:"claim_uuid"`
	ContractUUID    *uuid.UUID             `json:"contract_uuid"`
	InstructionUUID *uuid.UUID             `json:"instruction_uuid"`
	Paths           []string               `json:"paths"`
	Detail          null.String            `json:"detail"`
}

func (e EventPayload) String() string {
	res, _ := json.Marshal(e)
	return string(res)
}

func (e EventPayload) PrimaryKeyValues() []string {
	return []string{}
}

// The parameter is a plain []byte rather than json.RawMessage so that both a
// json.RawMessage and the mapper.JSON a repository model holds can be passed
// without a conversion at the call site.
func EventPayloadFromJSON(data []byte) EventPayload {
	entity := EventPayload{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		if err2 := mapper.FlexibleUnmarshal(data, &entity); err2 != nil {
			log.Printf("flexible unmarshal error EventPayloadFromJSON: %v\n", err2)
		}
	}
	return entity
}

func EventPayloadSliceFromJSON(data []byte) []EventPayload {
	entity := []EventPayload{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		entity = []EventPayload{}
		var rawSlice []json.RawMessage
		if err2 := json.Unmarshal(data, &rawSlice); err2 == nil {
			for _, raw := range rawSlice {
				item := EventPayload{}
				if err3 := mapper.FlexibleUnmarshal(raw, &item); err3 != nil {
					log.Printf("flexible unmarshal error EventPayloadSliceFromJSON item: %v\n", err3)
				}
				entity = append(entity, item)
			}
		}
	}
	return entity
}

func (e EventPayload) ToJSON() json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error EventPayloadToJSON: %v\n", err)
		return json.RawMessage("null")
	}
	return res
}

func EventPayloadToJSON(e EventPayload) json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error EventPayloadToJSON: %v\n", err)
		return json.RawMessage("null")
	}
	return res
}

// EventPayloadSliceToJSON serializes a ONE_TO_MANY embed for its JSON column.
// An absent embed is the EMPTY ARRAY, never a zero-length json.RawMessage: a
// zero-length value reaches the driver as the empty string, which is not valid
// JSON, so a create that simply omitted an optional array embed was rejected by
// the database ("invalid input syntax for type json", MySQL error 3140) and
// surfaced as a 500. "[]" is also exactly what an explicit `"field": []` stores,
// so the omitted and the explicitly-empty request round-trip to the same value.
func EventPayloadSliceToJSON(e []EventPayload) json.RawMessage {
	if e == nil {
		return json.RawMessage("[]")
	}
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error EventPayloadSliceToJSON: %v\n", err)
		return json.RawMessage("[]")
	}
	return res
}
