// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/mklfarha/metiche/backend/entity/agent"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchAgentByMemberUUIDAndClientKeyRequest struct {
	MemberUUID uuid.UUID
	ClientKey  string

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchAgentByMemberUUIDAndClientKeyRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("member_uuid", r.MemberUUID.String())

	return nil
}

type FetchAgentByMemberUUIDAndClientKeyResponse struct {
	Results []main_entity.Agent
}
