// Code generated by nuzur go-code-gen. DO NOT EDIT.

package claim_path

import (
	entitytypes "github.com/mklfarha/metiche/backend/entity/types"
)

func (e ClaimPath) FieldIdentifierToTypeMap() map[string]entitytypes.FieldType {
	return map[string]entitytypes.FieldType{
		"id":             entitytypes.StringFieldType,
		"claim_uuid":     entitytypes.StringFieldType,
		"project_uuid":   entitytypes.StringFieldType,
		"session_uuid":   entitytypes.StringFieldType,
		"member_uuid":    entitytypes.StringFieldType,
		"mode":           entitytypes.SingleEnumFieldType,
		"status":         entitytypes.SingleEnumFieldType,
		"expires_at":     entitytypes.TimestampFieldType,
		"pattern":        entitytypes.StringFieldType,
		"pattern_norm":   entitytypes.StringFieldType,
		"kind":           entitytypes.SingleEnumFieldType,
		"prefix":         entitytypes.StringFieldType,
		"suffix_pattern": entitytypes.StringFieldType,
		"depth":          entitytypes.IntFieldType,
		"ext":            entitytypes.StringFieldType,
		"created_at":     entitytypes.TimestampFieldType,
		"updated_at":     entitytypes.TimestampFieldType,
	}
}

func (e ClaimPath) OrderedFieldIdentifiers() []string {
	res := []string{}
	res = append(res, "id")
	res = append(res, "claim_uuid")
	res = append(res, "project_uuid")
	res = append(res, "session_uuid")
	res = append(res, "member_uuid")
	res = append(res, "mode")
	res = append(res, "status")
	res = append(res, "expires_at")
	res = append(res, "pattern")
	res = append(res, "pattern_norm")
	res = append(res, "kind")
	res = append(res, "prefix")
	res = append(res, "suffix_pattern")
	res = append(res, "depth")
	res = append(res, "ext")
	res = append(res, "created_at")
	res = append(res, "updated_at")

	return res
}

func (e ClaimPath) DependantFieldIdentifierToTypeMap() map[string]map[string]entitytypes.FieldType {
	res := make(map[string]map[string]entitytypes.FieldType)

	return res
}

func (e ClaimPath) EntityIdentifier() string {
	return "claim_path"
}

func (e ClaimPath) PrimaryKeyIdentifiers() []string {
	return []string{
		"id",
	}
}

func (e ClaimPath) ArrayFieldIdentifierToType() map[string]entitytypes.FieldType {
	res := make(map[string]entitytypes.FieldType)

	return res
}
