// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/mklfarha/metiche/backend/entity/decision_token"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchDecisionTokenByIDRequest struct {
	ID uuid.UUID
}

func (r FetchDecisionTokenByIDRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("id", r.ID.String())

	return nil
}

type FetchDecisionTokenByIDResponse struct {
	Results []main_entity.DecisionToken
}
