// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/mklfarha/metiche/backend/entity/intent"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchIntentByTeamUUIDAndKeyRequest struct {
	TeamUUID uuid.UUID
	Key      string

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchIntentByTeamUUIDAndKeyRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("team_uuid", r.TeamUUID.String())

	return nil
}

type FetchIntentByTeamUUIDAndKeyResponse struct {
	Results []main_entity.Intent
}
