// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/mklfarha/metiche/backend/entity/intent"

	"github.com/gofrs/uuid"
	"github.com/guregu/null/v6"
	"go.uber.org/zap/zapcore"
)

type FetchIntentByTeamUUIDAndExternalRefRequest struct {
	TeamUUID    uuid.UUID
	ExternalRef null.String

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchIntentByTeamUUIDAndExternalRefRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("team_uuid", r.TeamUUID.String())

	return nil
}

type FetchIntentByTeamUUIDAndExternalRefResponse struct {
	Results []main_entity.Intent
}
