// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/mklfarha/metiche/backend/entity/intent"

	"github.com/gofrs/uuid"
)

type UpsertRequest struct {
	Intent main_entity.Intent
}

type UpsertResponse struct {
	ID uuid.UUID
}
