// Code generated by nuzur go-code-gen. DO NOT EDIT.

package browser_session

import (
	"github.com/mklfarha/metiche/backend/entity/validation"
)

// Validate checks this BrowserSession against the schema's field type and
// type-config rules, aggregating every problem into a single *validation.Error.
// It mirrors the change-request data validation enforced in
// product/module/datavalidation, so data written through this API is held to
// the same rules. Generated by go-code-gen — do not edit.
func (e BrowserSession) Validate() error {
	c := validation.NewCollector()
	if e.ID.IsNil() {
		c.Require("browser_session.id")
	}
	if e.Key == "" {
		c.Require("browser_session.key")
	} else {
		c.Field("browser_session.key", validation.String(e.Key, 0, 32, ""))

	}
	if e.AccountUUID.IsNil() {
		c.Require("browser_session.account_uuid")
	}
	if e.SecretHash == "" {
		c.Require("browser_session.secret_hash")
	} else {
		c.Field("browser_session.secret_hash", validation.String(e.SecretHash, 0, 64, ""))

	}
	if e.AuthMethod.ToInt64() == 0 {
		c.Require("browser_session.auth_method")
	} else {
		c.Field("browser_session.auth_method", validation.EnumMember(e.AuthMethod.ToInt64(), []int64{0, 1, 2}, "browser_auth_method"))

	}
	if e.UserAgent.Valid && e.UserAgent.String != "" {
		c.Field("browser_session.user_agent", validation.String(e.UserAgent.String, 0, 200, ""))

	}
	if e.IpHint.Valid && e.IpHint.String != "" {
		c.Field("browser_session.ip_hint", validation.String(e.IpHint.String, 0, 64, ""))

	}
	if e.ExpiresAt.IsZero() {
		c.Require("browser_session.expires_at")
	}
	if e.EndReason.ToInt64() != 0 {
		c.Field("browser_session.end_reason", validation.EnumMember(e.EndReason.ToInt64(), []int64{0, 1, 2, 3, 4, 5}, "browser_session_end_reason"))

	}

	return c.Result()
}
