// Code generated by nuzur go-code-gen. DO NOT EDIT.

package limit_event

import (
	entitytypes "github.com/mklfarha/metiche/backend/entity/types"
)

func (e LimitEvent) FieldIdentifierToTypeMap() map[string]entitytypes.FieldType {
	return map[string]entitytypes.FieldType{
		"id":           entitytypes.StringFieldType,
		"team_uuid":    entitytypes.StringFieldType,
		"plan_uuid":    entitytypes.StringFieldType,
		"session_uuid": entitytypes.StringFieldType,
		"dimension":    entitytypes.StringFieldType,
		"observed":     entitytypes.IntFieldType,
		"allowed":      entitytypes.IntFieldType,
		"outcome":      entitytypes.SingleEnumFieldType,
		"note":         entitytypes.StringFieldType,
		"occurred_at":  entitytypes.TimestampFieldType,
		"created_at":   entitytypes.TimestampFieldType,
		"updated_at":   entitytypes.TimestampFieldType,
	}
}

func (e LimitEvent) OrderedFieldIdentifiers() []string {
	res := []string{}
	res = append(res, "id")
	res = append(res, "team_uuid")
	res = append(res, "plan_uuid")
	res = append(res, "session_uuid")
	res = append(res, "dimension")
	res = append(res, "observed")
	res = append(res, "allowed")
	res = append(res, "outcome")
	res = append(res, "note")
	res = append(res, "occurred_at")
	res = append(res, "created_at")
	res = append(res, "updated_at")

	return res
}

func (e LimitEvent) DependantFieldIdentifierToTypeMap() map[string]map[string]entitytypes.FieldType {
	res := make(map[string]map[string]entitytypes.FieldType)

	return res
}

func (e LimitEvent) EntityIdentifier() string {
	return "limit_event"
}

func (e LimitEvent) PrimaryKeyIdentifiers() []string {
	return []string{
		"id",
	}
}

func (e LimitEvent) ArrayFieldIdentifierToType() map[string]entitytypes.FieldType {
	res := make(map[string]entitytypes.FieldType)

	return res
}
