// Code generated by nuzur go-code-gen. DO NOT EDIT.

package member

import (
	entitytypes "github.com/mklfarha/metiche/backend/entity/types"
)

func (e Member) FieldIdentifierToTypeMap() map[string]entitytypes.FieldType {
	return map[string]entitytypes.FieldType{
		"id":           entitytypes.StringFieldType,
		"team_uuid":    entitytypes.StringFieldType,
		"key":          entitytypes.StringFieldType,
		"display_name": entitytypes.StringFieldType,
		"role":         entitytypes.SingleEnumFieldType,
		"last_seen_at": entitytypes.TimestampFieldType,
		"status":       entitytypes.SingleEnumFieldType,
		"created_at":   entitytypes.TimestampFieldType,
		"updated_at":   entitytypes.TimestampFieldType,
		"account_uuid": entitytypes.StringFieldType,
		"revoked_at":   entitytypes.TimestampFieldType,
	}
}

func (e Member) OrderedFieldIdentifiers() []string {
	res := []string{}
	res = append(res, "id")
	res = append(res, "team_uuid")
	res = append(res, "key")
	res = append(res, "display_name")
	res = append(res, "role")
	res = append(res, "last_seen_at")
	res = append(res, "status")
	res = append(res, "created_at")
	res = append(res, "updated_at")
	res = append(res, "account_uuid")
	res = append(res, "revoked_at")

	return res
}

func (e Member) DependantFieldIdentifierToTypeMap() map[string]map[string]entitytypes.FieldType {
	res := make(map[string]map[string]entitytypes.FieldType)

	return res
}

func (e Member) EntityIdentifier() string {
	return "member"
}

func (e Member) PrimaryKeyIdentifiers() []string {
	return []string{
		"id",
	}
}

func (e Member) ArrayFieldIdentifierToType() map[string]entitytypes.FieldType {
	res := make(map[string]entitytypes.FieldType)

	return res
}
