// Code generated by nuzur go-code-gen. DO NOT EDIT.

package conflict

import (
	"context"
	"errors"

	"github.com/mklfarha/metiche/backend/core/module/conflict/types"
	metichedb "github.com/mklfarha/metiche/backend/core/repository/gen"

	"github.com/mklfarha/metiche/backend/entity/conflict_evidence"

	"time"

	"github.com/mklfarha/metiche/backend/entity/mapper"
)

func (m *module) Update(
	ctx context.Context,
	req types.UpsertRequest,
	opts ...Option,
) (types.UpsertResponse, error) {
	optConfig := applyAllOptions(opts)

	tx := optConfig.SQLTx
	createdTx := false
	if tx == nil {
		ntx, err := m.repository.DB.Begin()
		if err != nil {
			return types.UpsertResponse{}, err
		}
		tx = ntx
		defer tx.Rollback()
		createdTx = true
	}

	qtx := m.repository.Queries.WithTx(tx)
	existing, err := qtx.FetchConflictByIDForUpdate(ctx,
		req.Conflict.ID.String(),
	)
	if err != nil {

		return types.UpsertResponse{}, err
	}

	if len(existing) == 0 {
		err := errors.New("entity not found")

		return types.UpsertResponse{}, err
	}

	// refresh server-managed timestamps that update on every write (updated_at)
	req.Conflict.UpdatedAt = time.Now()

	// validate the merged entity against the schema's field type/type-config rules
	if err := req.Conflict.Validate(); err != nil {

		return types.UpsertResponse{}, err
	}

	params := mapUpsertRequestToUpdateParams(req)
	err = qtx.UpdateConflict(
		ctx,
		params,
	)
	if err != nil {

		return types.UpsertResponse{}, err
	}

	if createdTx {
		err := tx.Commit()
		if err != nil {

			return types.UpsertResponse{}, err
		}
	}

	// The rows this module caches have changed, so everything it holds is
	// suspect: drop it rather than answer a later read from a snapshot that
	// predates this write. The cache is per entity, so this discards only this
	// entity's reads. (It is a no-op while a caller-supplied transaction is
	// still open — those reads bypass the cache anyway.)
	m.cache.Flush()

	return buildUpdateResponse(req), nil
}

func buildUpdateResponse(req types.UpsertRequest) types.UpsertResponse {
	return types.UpsertResponse{

		ID: req.Conflict.ID,
	}
}

func mapUpsertRequestToUpdateParams(req types.UpsertRequest) metichedb.UpdateConflictParams {
	return metichedb.UpdateConflictParams{
		ID: req.Conflict.ID.String(),

		TeamUUID: req.Conflict.TeamUUID.String(),

		ProjectUUID: req.Conflict.ProjectUUID.String(),

		Key: req.Conflict.Key,

		Kind: req.Conflict.Kind.ToInt64(),

		DedupeKey: req.Conflict.DedupeKey,

		Severity: req.Conflict.Severity.ToInt64(),

		Status: req.Conflict.Status.ToInt64(),

		DetectedBy: req.Conflict.DetectedBy.ToInt64(),

		DetectorRule: req.Conflict.DetectorRule,

		Confidence: req.Conflict.Confidence,

		Evidence: mapper.JSON(conflict_evidence.ConflictEvidenceToJSON(req.Conflict.Evidence)),

		SuggestedAction: req.Conflict.SuggestedAction,

		SuggestedYieldSessionUUID: mapper.UUIDPtrToNullString(req.Conflict.SuggestedYieldSessionUUID),

		SuggestedYieldReason: req.Conflict.SuggestedYieldReason,

		Resolution: req.Conflict.Resolution.ToNullInt(),

		ResolutionNote: req.Conflict.ResolutionNote,

		DismissReason: req.Conflict.DismissReason.ToNullInt(),

		ResolvedByMemberUUID: mapper.UUIDPtrToNullString(req.Conflict.ResolvedByMemberUUID),

		ResolvedAt: req.Conflict.ResolvedAt,

		OccurrenceCount: req.Conflict.OccurrenceCount,

		FirstDetectedAt: req.Conflict.FirstDetectedAt,

		LastDetectedAt: req.Conflict.LastDetectedAt,

		NotifiedAt: req.Conflict.NotifiedAt,

		MaxSeverityNotified: req.Conflict.MaxSeverityNotified.ToNullInt(),

		CreatedAt: req.Conflict.CreatedAt,

		UpdatedAt: req.Conflict.UpdatedAt,
	}
}
