// Code generated by nuzur go-code-gen. DO NOT EDIT.

package enums

import (
	"encoding/json"
	"github.com/guregu/null/v6"
	"log"
)

//go:generate go run github.com/dmarkham/enumer -type=DetectedBy -json
type DetectedBy int64

const (
	DETECTED_BY_INVALID = iota
	DETECTED_BY_SERVER
	DETECTED_BY_AGENT
	DETECTED_BY_HUMAN
)

func (e DetectedBy) ToInt64() int64 {
	return int64(e)
}

func (e DetectedBy) ToNullInt() null.Int {
	return null.NewInt(int64(e), true)
}

func DetectedByFromString(in string) DetectedBy {
	switch in {
	case "invalid":
		return DETECTED_BY_INVALID
	case "server":
		return DETECTED_BY_SERVER
	case "agent":
		return DETECTED_BY_AGENT
	case "human":
		return DETECTED_BY_HUMAN
	}
	return DETECTED_BY_INVALID
}

func DetectedByFromPointerString(in *string) DetectedBy {
	if in == nil {
		return DETECTED_BY_INVALID
	}
	return DetectedByFromString(*in)
}

func (e DetectedBy) String() string {
	switch e {
	case DETECTED_BY_INVALID:
		return "invalid"
	case DETECTED_BY_SERVER:
		return "server"
	case DETECTED_BY_AGENT:
		return "agent"
	case DETECTED_BY_HUMAN:
		return "human"
	}

	return "invalid"
}

func (e DetectedBy) StringPtr() *string {
	val := e.String()
	return &val
}

func DetectedBySliceToJSON(in []DetectedBy) json.RawMessage {
	res := make([]int64, len(in))
	for i, e := range in {
		res[i] = int64(e)
	}
	jr, err := json.Marshal(res)
	if err != nil {
		log.Printf("error marshaling DetectedBy slice to json: %v", err)
		// the empty ARRAY, not a zero-length RawMessage: the latter reaches the
		// driver as an empty string, which no JSON column accepts
		return json.RawMessage("[]")
	}
	return jr
}

func JSONToDetectedBySlice(in []byte) []DetectedBy {
	res := []int64{}
	// an absent column (NULL / empty / JSON null) is not a decode failure
	if len(in) == 0 || string(in) == "null" {
		return nil
	}
	err := json.Unmarshal(in, &res)
	if err != nil {
		log.Printf("error unmarshaling DetectedBy slice to int slice: %v", err)
		return nil
	}
	if len(res) == 0 {
		return nil
	}
	finalRes := []DetectedBy{}
	for _, r := range res {
		finalRes = append(finalRes, DetectedBy(r))
	}
	return finalRes
}
