// Code generated by nuzur go-code-gen. DO NOT EDIT.

package enums

import (
	"encoding/json"
	"github.com/guregu/null/v6"
	"log"
)

//go:generate go run github.com/dmarkham/enumer -type=LimitOutcome -json
type LimitOutcome int64

const (
	LIMIT_OUTCOME_INVALID = iota
	LIMIT_OUTCOME_WARNED
	LIMIT_OUTCOME_REFUSED
	LIMIT_OUTCOME_ALLOWED_OVER
)

func (e LimitOutcome) ToInt64() int64 {
	return int64(e)
}

func (e LimitOutcome) ToNullInt() null.Int {
	return null.NewInt(int64(e), true)
}

func LimitOutcomeFromString(in string) LimitOutcome {
	switch in {
	case "invalid":
		return LIMIT_OUTCOME_INVALID
	case "warned":
		return LIMIT_OUTCOME_WARNED
	case "refused":
		return LIMIT_OUTCOME_REFUSED
	case "allowed_over":
		return LIMIT_OUTCOME_ALLOWED_OVER
	}
	return LIMIT_OUTCOME_INVALID
}

func LimitOutcomeFromPointerString(in *string) LimitOutcome {
	if in == nil {
		return LIMIT_OUTCOME_INVALID
	}
	return LimitOutcomeFromString(*in)
}

func (e LimitOutcome) String() string {
	switch e {
	case LIMIT_OUTCOME_INVALID:
		return "invalid"
	case LIMIT_OUTCOME_WARNED:
		return "warned"
	case LIMIT_OUTCOME_REFUSED:
		return "refused"
	case LIMIT_OUTCOME_ALLOWED_OVER:
		return "allowed_over"
	}

	return "invalid"
}

func (e LimitOutcome) StringPtr() *string {
	val := e.String()
	return &val
}

func LimitOutcomeSliceToJSON(in []LimitOutcome) json.RawMessage {
	res := make([]int64, len(in))
	for i, e := range in {
		res[i] = int64(e)
	}
	jr, err := json.Marshal(res)
	if err != nil {
		log.Printf("error marshaling LimitOutcome slice to json: %v", err)
		// the empty ARRAY, not a zero-length RawMessage: the latter reaches the
		// driver as an empty string, which no JSON column accepts
		return json.RawMessage("[]")
	}
	return jr
}

func JSONToLimitOutcomeSlice(in []byte) []LimitOutcome {
	res := []int64{}
	// an absent column (NULL / empty / JSON null) is not a decode failure
	if len(in) == 0 || string(in) == "null" {
		return nil
	}
	err := json.Unmarshal(in, &res)
	if err != nil {
		log.Printf("error unmarshaling LimitOutcome slice to int slice: %v", err)
		return nil
	}
	if len(res) == 0 {
		return nil
	}
	finalRes := []LimitOutcome{}
	for _, r := range res {
		finalRes = append(finalRes, LimitOutcome(r))
	}
	return finalRes
}
