// Code generated by nuzur go-code-gen. DO NOT EDIT.

package enums

import (
	"encoding/json"
	"github.com/guregu/null/v6"
	"log"
)

//go:generate go run github.com/dmarkham/enumer -type=SessionStatus -json
type SessionStatus int64

const (
	SESSION_STATUS_INVALID = iota
	SESSION_STATUS_LIVE
	SESSION_STATUS_STALE
	SESSION_STATUS_ENDED
	SESSION_STATUS_ABANDONED
)

func (e SessionStatus) ToInt64() int64 {
	return int64(e)
}

func (e SessionStatus) ToNullInt() null.Int {
	return null.NewInt(int64(e), true)
}

func SessionStatusFromString(in string) SessionStatus {
	switch in {
	case "invalid":
		return SESSION_STATUS_INVALID
	case "live":
		return SESSION_STATUS_LIVE
	case "stale":
		return SESSION_STATUS_STALE
	case "ended":
		return SESSION_STATUS_ENDED
	case "abandoned":
		return SESSION_STATUS_ABANDONED
	}
	return SESSION_STATUS_INVALID
}

func SessionStatusFromPointerString(in *string) SessionStatus {
	if in == nil {
		return SESSION_STATUS_INVALID
	}
	return SessionStatusFromString(*in)
}

func (e SessionStatus) String() string {
	switch e {
	case SESSION_STATUS_INVALID:
		return "invalid"
	case SESSION_STATUS_LIVE:
		return "live"
	case SESSION_STATUS_STALE:
		return "stale"
	case SESSION_STATUS_ENDED:
		return "ended"
	case SESSION_STATUS_ABANDONED:
		return "abandoned"
	}

	return "invalid"
}

func (e SessionStatus) StringPtr() *string {
	val := e.String()
	return &val
}

func SessionStatusSliceToJSON(in []SessionStatus) json.RawMessage {
	res := make([]int64, len(in))
	for i, e := range in {
		res[i] = int64(e)
	}
	jr, err := json.Marshal(res)
	if err != nil {
		log.Printf("error marshaling SessionStatus slice to json: %v", err)
		// the empty ARRAY, not a zero-length RawMessage: the latter reaches the
		// driver as an empty string, which no JSON column accepts
		return json.RawMessage("[]")
	}
	return jr
}

func JSONToSessionStatusSlice(in []byte) []SessionStatus {
	res := []int64{}
	// an absent column (NULL / empty / JSON null) is not a decode failure
	if len(in) == 0 || string(in) == "null" {
		return nil
	}
	err := json.Unmarshal(in, &res)
	if err != nil {
		log.Printf("error unmarshaling SessionStatus slice to int slice: %v", err)
		return nil
	}
	if len(res) == 0 {
		return nil
	}
	finalRes := []SessionStatus{}
	for _, r := range res {
		finalRes = append(finalRes, SessionStatus(r))
	}
	return finalRes
}
