// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/mklfarha/metiche/backend/entity/conflict_participant"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchConflictParticipantByIDRequest struct {
	ID uuid.UUID
}

func (r FetchConflictParticipantByIDRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("id", r.ID.String())

	return nil
}

type FetchConflictParticipantByIDResponse struct {
	Results []main_entity.ConflictParticipant
}
