// Code generated by nuzur go-code-gen. DO NOT EDIT.

package team

import (
	"context"
	"fmt"

	"github.com/mklfarha/metiche/backend/core/module/team/types"

	"errors"
	metichedb "github.com/mklfarha/metiche/backend/core/repository/gen"
)

func (m *module) FetchTeamByJoinCode(
	ctx context.Context,
	req types.FetchTeamByJoinCodeRequest,
	opts ...Option,
) (types.FetchTeamByJoinCodeResponse, error) {

	resolvedOpts := applyAllOptions(opts)
	queries := m.repository.Queries
	if resolvedOpts.SQLTx != nil {
		queries = queries.WithTx(resolvedOpts.SQLTx)
	}
	// A read inside a transaction must observe that transaction's own
	// uncommitted writes, so it can neither be served from the shared cache nor
	// be collapsed into another caller's in-flight query.
	skipShared := resolvedOpts.SkipCache || resolvedOpts.SQLTx != nil
	cacheKey := fmt.Sprintf("FetchTeamByJoinCode:%v", req)
	if !skipShared {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.FetchTeamByJoinCodeResponse), nil
		}
	}
	fetch := func() (any, error) {
		if req.OrderBy == "" {
			models, err := queries.FetchTeamByJoinCode(
				ctx,
				metichedb.FetchTeamByJoinCodeParams{
					JoinCode: req.JoinCode,

					Offset: req.Offset,
					Limit:  req.Limit,
				},
			)

			if err != nil {

				return types.FetchTeamByJoinCodeResponse{}, err
			}
			return types.FetchTeamByJoinCodeResponse{
				Results: mapModelsToEntities(models),
			}, nil
		}

		err := errors.New("could not process request")

		return types.FetchTeamByJoinCodeResponse{}, err
	} // end fetch
	var v any
	var fetchErr error
	if skipShared {
		v, fetchErr = fetch()
	} else {
		v, fetchErr, _ = m.sg.Do(cacheKey, fetch)
	}
	if fetchErr != nil {
		return types.FetchTeamByJoinCodeResponse{}, fetchErr
	}
	result := v.(types.FetchTeamByJoinCodeResponse)
	if !skipShared {
		m.cache.Set(cacheKey, result, 0)
	}
	return result, nil

}
