// Code generated by nuzur go-code-gen. DO NOT EDIT.

package session

import (
	"context"
	"errors"

	"github.com/mklfarha/metiche/backend/core/module/session/types"
	metichedb "github.com/mklfarha/metiche/backend/core/repository/gen"

	"time"

	"github.com/mklfarha/metiche/backend/entity/mapper"
)

func (m *module) Update(
	ctx context.Context,
	req types.UpsertRequest,
	opts ...Option,
) (types.UpsertResponse, error) {
	optConfig := applyAllOptions(opts)

	tx := optConfig.SQLTx
	createdTx := false
	if tx == nil {
		ntx, err := m.repository.DB.Begin()
		if err != nil {
			return types.UpsertResponse{}, err
		}
		tx = ntx
		defer tx.Rollback()
		createdTx = true
	}

	qtx := m.repository.Queries.WithTx(tx)
	existing, err := qtx.FetchSessionByIDForUpdate(ctx,
		req.Session.ID.String(),
	)
	if err != nil {

		return types.UpsertResponse{}, err
	}

	if len(existing) == 0 {
		err := errors.New("entity not found")

		return types.UpsertResponse{}, err
	}

	// refresh server-managed timestamps that update on every write (updated_at)
	req.Session.UpdatedAt = time.Now()

	// validate the merged entity against the schema's field type/type-config rules
	if err := req.Session.Validate(); err != nil {

		return types.UpsertResponse{}, err
	}

	params := mapUpsertRequestToUpdateParams(req)
	err = qtx.UpdateSession(
		ctx,
		params,
	)
	if err != nil {

		return types.UpsertResponse{}, err
	}

	if createdTx {
		err := tx.Commit()
		if err != nil {

			return types.UpsertResponse{}, err
		}
	}

	// The rows this module caches have changed, so everything it holds is
	// suspect: drop it rather than answer a later read from a snapshot that
	// predates this write. The cache is per entity, so this discards only this
	// entity's reads. (It is a no-op while a caller-supplied transaction is
	// still open — those reads bypass the cache anyway.)
	m.cache.Flush()

	return buildUpdateResponse(req), nil
}

func buildUpdateResponse(req types.UpsertRequest) types.UpsertResponse {
	return types.UpsertResponse{

		ID: req.Session.ID,
	}
}

func mapUpsertRequestToUpdateParams(req types.UpsertRequest) metichedb.UpdateSessionParams {
	return metichedb.UpdateSessionParams{
		ID: req.Session.ID.String(),

		TeamUUID: req.Session.TeamUUID.String(),

		ProjectUUID: req.Session.ProjectUUID.String(),

		AgentUUID: req.Session.AgentUUID.String(),

		MemberUUID: req.Session.MemberUUID.String(),

		Key: req.Session.Key,

		Branch: req.Session.Branch,

		BaseCommit: req.Session.BaseCommit,

		HeadCommit: req.Session.HeadCommit,

		Goal: req.Session.Goal,

		Status: req.Session.Status.ToInt64(),

		StatusLine: req.Session.StatusLine,

		CurrentIntentUUID: mapper.UUIDPtrToNullString(req.Session.CurrentIntentUUID),

		StartedAt: req.Session.StartedAt,

		LastHeartbeatAt: req.Session.LastHeartbeatAt,

		EndedAt: req.Session.EndedAt,

		Outcome: req.Session.Outcome.ToNullInt(),

		OutcomeNote: req.Session.OutcomeNote,

		CreatedAt: req.Session.CreatedAt,

		UpdatedAt: req.Session.UpdatedAt,
	}
}
