// Code generated by nuzur go-code-gen. DO NOT EDIT.

package server

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/http"

	claimmodule "github.com/mklfarha/metiche/backend/core/module/claim"
	"github.com/mklfarha/metiche/backend/core/module/claim/types"
	main_entity "github.com/mklfarha/metiche/backend/entity/claim"
)

func (h *handlers) CreateClaim(w http.ResponseWriter, r *http.Request) {
	var item main_entity.Claim
	if err := json.NewDecoder(r.Body).Decode(&item); err != nil {
		writeProblem(w, http.StatusBadRequest, err)
		return
	}

	res, err := h.core.Claim().Insert(r.Context(), types.UpsertRequest{
		Claim: item,
	})
	if err != nil {
		writeProblem(w, http.StatusInternalServerError, err)
		return
	}

	fetchRes, err := h.core.Claim().FetchClaimByID(r.Context(), types.FetchClaimByIDRequest(res), claimmodule.WithSkipCache())
	if err != nil {
		writeProblem(w, http.StatusInternalServerError, err)
		return
	}

	if len(fetchRes.Results) == 0 {
		writeProblem(w, http.StatusInternalServerError, errors.New("entity not found after insert"))
		return
	}

	createdEntity := fetchRes.Results[0]

	// Location header
	location := fmt.Sprintf("%s/%v/", r.URL.Path, createdEntity.ID)
	w.Header().Set("Location", location)

	writeJSON(w, http.StatusCreated, createdEntity)
}
