// Code generated by nuzur go-code-gen. DO NOT EDIT.

package server

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/http"

	decision_pathmodule "github.com/mklfarha/metiche/backend/core/module/decision_path"
	"github.com/mklfarha/metiche/backend/core/module/decision_path/types"
	main_entity "github.com/mklfarha/metiche/backend/entity/decision_path"
)

func (h *handlers) CreateDecisionPath(w http.ResponseWriter, r *http.Request) {
	var item main_entity.DecisionPath
	if err := json.NewDecoder(r.Body).Decode(&item); err != nil {
		writeProblem(w, http.StatusBadRequest, err)
		return
	}

	res, err := h.core.DecisionPath().Insert(r.Context(), types.UpsertRequest{
		DecisionPath: item,
	})
	if err != nil {
		writeProblem(w, http.StatusInternalServerError, err)
		return
	}

	fetchRes, err := h.core.DecisionPath().FetchDecisionPathByID(r.Context(), types.FetchDecisionPathByIDRequest(res), decision_pathmodule.WithSkipCache())
	if err != nil {
		writeProblem(w, http.StatusInternalServerError, err)
		return
	}

	if len(fetchRes.Results) == 0 {
		writeProblem(w, http.StatusInternalServerError, errors.New("entity not found after insert"))
		return
	}

	createdEntity := fetchRes.Results[0]

	// Location header
	location := fmt.Sprintf("%s/%v/", r.URL.Path, createdEntity.ID)
	w.Header().Set("Location", location)

	writeJSON(w, http.StatusCreated, createdEntity)
}
