// Code generated by nuzur go-code-gen. DO NOT EDIT.

package server

import (
	"fmt"
	"log"
	"net/http"

	"go.einride.tech/aip/filtering"
	"go.einride.tech/aip/ordering"

	contract_assertionmodule "github.com/mklfarha/metiche/backend/core/module/contract_assertion"
	"github.com/mklfarha/metiche/backend/core/module/contract_assertion/types"
	main_entity "github.com/mklfarha/metiche/backend/entity/contract_assertion"
)

func (h *handlers) ListContractAssertion(w http.ResponseWriter, r *http.Request) {
	defaultPageSize := int32(10)
	maxPageSize := int32(100)

	lp, err := parseListParams(r, defaultPageSize, maxPageSize)
	if err != nil {
		writeProblem(w, http.StatusBadRequest, err)
		return
	}

	offset, err := parsePageTokenOffset(lp.pageToken)
	if err != nil {
		writeProblem(w, http.StatusBadRequest, fmt.Errorf("invalid page token: %w", err))
		return
	}

	declarations := contract_assertionDeclarations()
	filter, err := filtering.ParseFilter(lp, declarations)
	if err != nil {
		writeProblem(w, http.StatusBadRequest, fmt.Errorf("invalid filter expression: %w", err))
		return
	}

	orderBy, err := ordering.ParseOrderBy(lp)
	if err != nil {
		writeProblem(w, http.StatusBadRequest, fmt.Errorf("invalid order_by expression: %w", err))
		return
	}

	req := types.ListRequest{
		Offset:                offset,
		PageSize:              lp.GetPageSize(),
		Filter:                filter,
		FilteringDeclarations: declarations,
		EnumValues:            contract_assertionEnumValues(),
		OrderBy:               orderBy,
		IncludeFields:         lp.includeFields,
		ExcludeFields:         lp.excludeFields,
	}

	var result types.ListResponse
	if lp.skipCache {
		result, err = h.core.ContractAssertion().List(r.Context(), req, contract_assertionmodule.WithSkipCache())
	} else {
		result, err = h.core.ContractAssertion().List(r.Context(), req)
	}
	if err != nil {
		// A filter or order_by the clause builder cannot express is the caller's
		// error, not the server's: statusForError turns it into a 400.
		writeProblem(w, statusForError(err), err)
		return
	}

	resp := ListEnvelope[main_entity.ContractAssertion]{
		Items: result.ContractAssertion,
	}
	if result.HasNextPage {
		resp.NextPageToken = encodePageToken(offset + int64(lp.GetPageSize()))
	}

	writeJSON(w, http.StatusOK, resp)
}

func contract_assertionDeclarations() *filtering.Declarations {
	declarations, err := filtering.NewDeclarations(
		filtering.DeclareStandardFunctions(),
		filtering.DeclareIdent("true", filtering.TypeBool),
		filtering.DeclareIdent("false", filtering.TypeBool),

		// contract_assertion

		filtering.DeclareIdent("id", filtering.TypeString),

		filtering.DeclareIdent("contract_uuid", filtering.TypeString),

		filtering.DeclareIdent("team_uuid", filtering.TypeString),

		filtering.DeclareIdent("project_uuid", filtering.TypeString),

		filtering.DeclareIdent("session_uuid", filtering.TypeString),

		filtering.DeclareIdent("member_uuid", filtering.TypeString),

		// An enum is filtered by its VALUE over REST — either quoted
		// (status = "active", matched case-insensitively against every spelling
		// in contract_assertionEnumValues) or as the generated value name ident
		// (status = STATUS_ACTIVE, the same spelling gRPC accepts). Both are
		// strings to the type checker; the number they stand for is resolved
		// from the value table, not from this declaration.
		filtering.DeclareIdent("role", filtering.TypeString),
		filtering.DeclareIdent("ASSERTION_ROLE_INVALID", filtering.TypeString),
		filtering.DeclareIdent("ASSERTION_ROLE_PRODUCES", filtering.TypeString),
		filtering.DeclareIdent("ASSERTION_ROLE_CONSUMES", filtering.TypeString),

		filtering.DeclareIdent("shape_hash", filtering.TypeString),

		filtering.DeclareIdent("shape_fingerprint", filtering.TypeString),

		// An enum is filtered by its VALUE over REST — either quoted
		// (status = "active", matched case-insensitively against every spelling
		// in contract_assertionEnumValues) or as the generated value name ident
		// (status = STATUS_ACTIVE, the same spelling gRPC accepts). Both are
		// strings to the type checker; the number they stand for is resolved
		// from the value table, not from this declaration.
		filtering.DeclareIdent("status", filtering.TypeString),
		filtering.DeclareIdent("ASSERTION_STATUS_INVALID", filtering.TypeString),
		filtering.DeclareIdent("ASSERTION_STATUS_ACTIVE", filtering.TypeString),
		filtering.DeclareIdent("ASSERTION_STATUS_SUPERSEDED", filtering.TypeString),
		filtering.DeclareIdent("ASSERTION_STATUS_WITHDRAWN", filtering.TypeString),

		filtering.DeclareIdent("revision", filtering.TypeInt),

		filtering.DeclareIdent("active_marker", filtering.TypeInt),

		filtering.DeclareIdent("asserted_at", filtering.TypeTimestamp),

		filtering.DeclareIdent("superseded_by_uuid", filtering.TypeString),

		filtering.DeclareIdent("created_at", filtering.TypeTimestamp),

		filtering.DeclareIdent("updated_at", filtering.TypeTimestamp),
	)
	if err != nil {
		log.Printf("error creating declarations for contract_assertion: %v", err)
	}
	return declarations
}

// contract_assertionEnumValues maps each enum filter field to every accepted
// spelling of its values and the number the column stores. REST generates no
// protobuf enum types (an app built with --api rest has no proto package at
// all), so this table — not the filter declarations — is what makes an enum
// filter resolvable here.
func contract_assertionEnumValues() map[string]map[string]int64 {
	return map[string]map[string]int64{

		"role": {
			"invalid":                 0,
			"ASSERTION_ROLE_INVALID":  0,
			"produces":                1,
			"ASSERTION_ROLE_PRODUCES": 1,
			"consumes":                2,
			"ASSERTION_ROLE_CONSUMES": 2,
		},

		"status": {
			"invalid":                     0,
			"ASSERTION_STATUS_INVALID":    0,
			"active":                      1,
			"ASSERTION_STATUS_ACTIVE":     1,
			"superseded":                  2,
			"ASSERTION_STATUS_SUPERSEDED": 2,
			"withdrawn":                   3,
			"ASSERTION_STATUS_WITHDRAWN":  3,
		},
	}
}
