// Code generated by nuzur go-code-gen. DO NOT EDIT.

package board_login_link

import (
	metichedb "github.com/mklfarha/metiche/backend/core/repository/gen"
	main_entity "github.com/mklfarha/metiche/backend/entity/board_login_link"

	"github.com/mklfarha/metiche/backend/entity/mapper"

	"github.com/guregu/null/v6"
	"github.com/mklfarha/metiche/backend/enums"
)

func mapModelsToEntities(models []metichedb.BoardLoginLink) []main_entity.BoardLoginLink {
	result := []main_entity.BoardLoginLink{}
	for _, p := range models {
		result = append(result, mapModelToEntity(p))
	}
	return result
}

func mapModelToEntity(m metichedb.BoardLoginLink) main_entity.BoardLoginLink {
	return main_entity.BoardLoginLink{
		ID:           mapper.StringToUUID(m.ID),
		AccountUUID:  mapper.StringToUUID(m.AccountUUID),
		AgentUUID:    mapper.StringToUUID(m.AgentUUID),
		SecretHash:   m.SecretHash,
		RedirectPath: m.RedirectPath,
		RequestedVia: enums.BoardLinkSource(m.RequestedVia),
		ExpiresAt:    m.ExpiresAt,
		ConsumedAt:   null.NewTime(m.ConsumedAt.Time, m.ConsumedAt.Valid),
		CreatedAt:    m.CreatedAt,
		UpdatedAt:    m.UpdatedAt,
	}
}
