// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/mklfarha/metiche/backend/entity/claim"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchClaimByIDRequest struct {
	ID uuid.UUID
}

func (r FetchClaimByIDRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("id", r.ID.String())

	return nil
}

type FetchClaimByIDResponse struct {
	Results []main_entity.Claim
}
