// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/mklfarha/metiche/backend/entity/claim"

	"github.com/gofrs/uuid"
)

type UpsertRequest struct {
	Claim main_entity.Claim
}

type UpsertResponse struct {
	ID uuid.UUID
}
