// Code generated by nuzur go-code-gen. DO NOT EDIT.

package conflict_participant

import (
	"context"
	"errors"

	"github.com/mklfarha/metiche/backend/core/module/conflict_participant/types"
	metichedb "github.com/mklfarha/metiche/backend/core/repository/gen"

	"time"
)

func (m *module) Update(
	ctx context.Context,
	req types.UpsertRequest,
	opts ...Option,
) (types.UpsertResponse, error) {
	optConfig := applyAllOptions(opts)

	tx := optConfig.SQLTx
	createdTx := false
	if tx == nil {
		ntx, err := m.repository.DB.Begin()
		if err != nil {
			return types.UpsertResponse{}, err
		}
		tx = ntx
		defer tx.Rollback()
		createdTx = true
	}

	qtx := m.repository.Queries.WithTx(tx)
	existing, err := qtx.FetchConflictParticipantByIDForUpdate(ctx,
		req.ConflictParticipant.ID.String(),
	)
	if err != nil {

		return types.UpsertResponse{}, err
	}

	if len(existing) == 0 {
		err := errors.New("entity not found")

		return types.UpsertResponse{}, err
	}

	// refresh server-managed timestamps that update on every write (updated_at)
	req.ConflictParticipant.UpdatedAt = time.Now()

	// validate the merged entity against the schema's field type/type-config rules
	if err := req.ConflictParticipant.Validate(); err != nil {

		return types.UpsertResponse{}, err
	}

	params := mapUpsertRequestToUpdateParams(req)
	err = qtx.UpdateConflictParticipant(
		ctx,
		params,
	)
	if err != nil {

		return types.UpsertResponse{}, err
	}

	if createdTx {
		err := tx.Commit()
		if err != nil {

			return types.UpsertResponse{}, err
		}
	}

	// The rows this module caches have changed, so everything it holds is
	// suspect: drop it rather than answer a later read from a snapshot that
	// predates this write. The cache is per entity, so this discards only this
	// entity's reads. (It is a no-op while a caller-supplied transaction is
	// still open — those reads bypass the cache anyway.)
	m.cache.Flush()

	return buildUpdateResponse(req), nil
}

func buildUpdateResponse(req types.UpsertRequest) types.UpsertResponse {
	return types.UpsertResponse{

		ID: req.ConflictParticipant.ID,
	}
}

func mapUpsertRequestToUpdateParams(req types.UpsertRequest) metichedb.UpdateConflictParticipantParams {
	return metichedb.UpdateConflictParticipantParams{
		ID: req.ConflictParticipant.ID.String(),

		ConflictUUID: req.ConflictParticipant.ConflictUUID.String(),

		TeamUUID: req.ConflictParticipant.TeamUUID.String(),

		SessionUUID: req.ConflictParticipant.SessionUUID.String(),

		AgentUUID: req.ConflictParticipant.AgentUUID.String(),

		MemberUUID: req.ConflictParticipant.MemberUUID.String(),

		SubjectKind: req.ConflictParticipant.SubjectKind.ToInt64(),

		SubjectUUID: req.ConflictParticipant.SubjectUUID.String(),

		Role: req.ConflictParticipant.Role.ToInt64(),

		NotifiedAt: req.ConflictParticipant.NotifiedAt,

		AckedAt: req.ConflictParticipant.AckedAt,

		Response: req.ConflictParticipant.Response.ToNullInt(),

		CreatedAt: req.ConflictParticipant.CreatedAt,

		UpdatedAt: req.ConflictParticipant.UpdatedAt,
	}
}
