// Code generated by nuzur go-code-gen. DO NOT EDIT.

package conflict_participant

import (
	"context"

	"github.com/gofrs/uuid"

	"github.com/mklfarha/metiche/backend/core/module/conflict_participant/types"
)

func (m *module) Upsert(
	ctx context.Context,
	req types.UpsertRequest,
	opts ...Option,
) (types.UpsertResponse, error) {
	// check if primary keys are set to determine if this is an insert or update
	isInsert := true

	if req.ConflictParticipant.ID != uuid.Nil {
		isInsert = false
	}

	if isInsert {
		// PK UUIDs are auto-generated inside Insert when not supplied, so the
		// gRPC Create path (which calls Insert directly) also gets a valid UUID.
		return m.Insert(ctx, req, opts...)
	}

	return m.Update(ctx, req, opts...)
}
