-- Code generated by nuzur go-code-gen. DO NOT EDIT.
CREATE TABLE IF NOT EXISTS `team` (
    `id` CHAR(36) NOT NULL,
    `name` VARCHAR(120) NOT NULL,
    `slug` VARCHAR(512) NOT NULL,
    `join_code` VARCHAR(16) NOT NULL,
    `join_code_rotated_at` DATETIME,
    `sequence` BIGINT NOT NULL DEFAULT 0,
    `board_revision` BIGINT NOT NULL DEFAULT 0,
    `settings` JSON,
    `status` INT NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `uq_team_slug` (`slug`),
    UNIQUE INDEX `uq_team_join_code` (`join_code`)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `member` (
    `id` CHAR(36) NOT NULL,
    `team_uuid` CHAR(36) NOT NULL,
    `key` VARCHAR(32) NOT NULL,
    `display_name` VARCHAR(120) NOT NULL,
    `role` INT NOT NULL,
    `last_seen_at` DATETIME,
    `status` INT NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `uq_member_team_key` (`team_uuid`, `key`),
    CONSTRAINT `team_has_members`
        FOREIGN KEY (`team_uuid`)
        REFERENCES `team` (`id`)
        ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `project` (
    `id` CHAR(36) NOT NULL,
    `team_uuid` CHAR(36) NOT NULL,
    `key` VARCHAR(512) NOT NULL,
    `name` VARCHAR(120) NOT NULL,
    `repo_url` VARCHAR(512),
    `default_branch` VARCHAR(120),
    `ignore_patterns` JSON,
    `hotspot_patterns` JSON,
    `case_insensitive_paths` TINYINT(1) NOT NULL DEFAULT 1,
    `status` INT NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `cadence` INT NOT NULL DEFAULT 2,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `uq_project_team_key` (`team_uuid`, `key`),
    CONSTRAINT `team_has_projects`
        FOREIGN KEY (`team_uuid`)
        REFERENCES `team` (`id`)
        ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `agent` (
    `id` CHAR(36) NOT NULL,
    `team_uuid` CHAR(36) NOT NULL,
    `member_uuid` CHAR(36) NOT NULL,
    `key` VARCHAR(32) NOT NULL,
    `label` VARCHAR(80) NOT NULL,
    `client_kind` VARCHAR(60),
    `token_hash` VARCHAR(64) NOT NULL,
    `client_key` VARCHAR(120) NOT NULL,
    `status` INT NOT NULL,
    `last_seen_at` DATETIME,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `uq_agent_member_client` (`member_uuid`, `client_key`),
    CONSTRAINT `member_has_agents`
        FOREIGN KEY (`member_uuid`)
        REFERENCES `member` (`id`)
        ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `contract` (
    `id` CHAR(36) NOT NULL,
    `team_uuid` CHAR(36) NOT NULL,
    `project_uuid` CHAR(36) NOT NULL,
    `key` VARCHAR(255) NOT NULL,
    `key_norm` VARCHAR(255) NOT NULL,
    `kind` INT NOT NULL,
    `status` INT NOT NULL,
    `title` VARCHAR(200),
    `notes` TEXT,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `uq_contract_key_norm` (`project_uuid`, `key_norm`),
    CONSTRAINT `project_has_contracts`
        FOREIGN KEY (`project_uuid`)
        REFERENCES `project` (`id`)
        ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `decision` (
    `id` CHAR(36) NOT NULL,
    `team_uuid` CHAR(36) NOT NULL,
    `project_uuid` CHAR(36),
    `key` VARCHAR(80) NOT NULL,
    `title` VARCHAR(140) NOT NULL,
    `statement` VARCHAR(400) NOT NULL,
    `rationale` TEXT,
    `status` INT NOT NULL,
    `always_show` TINYINT(1) NOT NULL DEFAULT 0,
    `supersedes_uuid` CHAR(36),
    `superseded_by_uuid` CHAR(36),
    `decided_by_member_uuid` CHAR(36),
    `decided_at` DATETIME,
    `revision` INT NOT NULL DEFAULT 1,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `idx_decision_always_show` (`team_uuid`, `status`, `always_show`),
    UNIQUE INDEX `uq_decision_team_key` (`team_uuid`, `key`),
    CONSTRAINT `team_has_decisions`
        FOREIGN KEY (`team_uuid`)
        REFERENCES `team` (`id`)
        ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `decision_path` (
    `id` CHAR(36) NOT NULL,
    `decision_uuid` CHAR(36) NOT NULL,
    `team_uuid` CHAR(36) NOT NULL,
    `project_uuid` CHAR(36),
    `pattern` VARCHAR(400) NOT NULL,
    `pattern_norm` VARCHAR(400) NOT NULL,
    `kind` INT NOT NULL,
    `prefix` VARCHAR(400) NOT NULL,
    `depth` SMALLINT NOT NULL DEFAULT 0,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `idx_decision_path_scan` (`team_uuid`, `prefix`),
    CONSTRAINT `decision_has_paths`
        FOREIGN KEY (`decision_uuid`)
        REFERENCES `decision` (`id`)
        ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `decision_token` (
    `id` CHAR(36) NOT NULL,
    `decision_uuid` CHAR(36) NOT NULL,
    `team_uuid` CHAR(36) NOT NULL,
    `project_uuid` CHAR(36),
    `token` VARCHAR(32) NOT NULL,
    `weight` SMALLINT NOT NULL DEFAULT 1,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `idx_decision_token_lookup` (`team_uuid`, `token`),
    CONSTRAINT `decision_has_tokens`
        FOREIGN KEY (`decision_uuid`)
        REFERENCES `decision` (`id`)
        ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `session` (
    `id` CHAR(36) NOT NULL,
    `team_uuid` CHAR(36) NOT NULL,
    `project_uuid` CHAR(36) NOT NULL,
    `agent_uuid` CHAR(36) NOT NULL,
    `member_uuid` CHAR(36) NOT NULL,
    `key` VARCHAR(32) NOT NULL,
    `branch` VARCHAR(200),
    `base_commit` VARCHAR(64),
    `head_commit` VARCHAR(64),
    `goal` VARCHAR(280),
    `status` INT NOT NULL,
    `status_line` VARCHAR(120),
    `current_intent_uuid` CHAR(36),
    `started_at` DATETIME,
    `last_heartbeat_at` DATETIME,
    `ended_at` DATETIME,
    `outcome` INT,
    `outcome_note` VARCHAR(400),
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `idx_session_liveness` (`team_uuid`, `status`, `last_heartbeat_at`),
    INDEX `idx_session_project_status` (`project_uuid`, `status`),
    UNIQUE INDEX `uq_session_team_key` (`team_uuid`, `key`),
    CONSTRAINT `project_has_sessions`
        FOREIGN KEY (`project_uuid`)
        REFERENCES `project` (`id`)
        ON DELETE CASCADE,
    CONSTRAINT `agent_has_sessions`
        FOREIGN KEY (`agent_uuid`)
        REFERENCES `agent` (`id`)
        ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `intent` (
    `id` CHAR(36) NOT NULL,
    `team_uuid` CHAR(36) NOT NULL,
    `project_uuid` CHAR(36) NOT NULL,
    `session_uuid` CHAR(36) NOT NULL,
    `member_uuid` CHAR(36) NOT NULL,
    `key` VARCHAR(32) NOT NULL,
    `summary` VARCHAR(280) NOT NULL,
    `detail` TEXT,
    `kind` INT NOT NULL,
    `status` INT NOT NULL,
    `external_ref` VARCHAR(120),
    `revision` INT NOT NULL DEFAULT 1,
    `declared_at` DATETIME,
    `started_at` DATETIME,
    `ended_at` DATETIME,
    `expires_at` DATETIME,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `idx_intent_live` (`project_uuid`, `status`, `expires_at`),
    INDEX `idx_intent_external_ref` (`team_uuid`, `external_ref`),
    UNIQUE INDEX `uq_intent_team_key` (`team_uuid`, `key`),
    CONSTRAINT `session_has_intents`
        FOREIGN KEY (`session_uuid`)
        REFERENCES `session` (`id`)
        ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `claim` (
    `id` CHAR(36) NOT NULL,
    `team_uuid` CHAR(36) NOT NULL,
    `project_uuid` CHAR(36) NOT NULL,
    `session_uuid` CHAR(36) NOT NULL,
    `member_uuid` CHAR(36) NOT NULL,
    `intent_uuid` CHAR(36),
    `key` VARCHAR(32) NOT NULL,
    `mode` INT NOT NULL,
    `status` INT NOT NULL,
    `ttl_seconds` INT NOT NULL DEFAULT 900,
    `expires_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `hard_expires_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `breadth_score` SMALLINT NOT NULL DEFAULT 0,
    `released_at` DATETIME,
    `release_reason` VARCHAR(200),
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `idx_claim_sweeper` (`project_uuid`, `status`, `expires_at`),
    UNIQUE INDEX `uq_claim_team_key` (`team_uuid`, `key`),
    CONSTRAINT `session_has_claims`
        FOREIGN KEY (`session_uuid`)
        REFERENCES `session` (`id`)
        ON DELETE CASCADE,
    CONSTRAINT `intent_has_claims`
        FOREIGN KEY (`intent_uuid`)
        REFERENCES `intent` (`id`)
        ON DELETE SET NULL
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `claim_path` (
    `id` CHAR(36) NOT NULL,
    `claim_uuid` CHAR(36) NOT NULL,
    `project_uuid` CHAR(36) NOT NULL,
    `session_uuid` CHAR(36) NOT NULL,
    `member_uuid` CHAR(36) NOT NULL,
    `mode` INT NOT NULL,
    `status` INT NOT NULL,
    `expires_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `pattern` VARCHAR(400) NOT NULL,
    `pattern_norm` VARCHAR(400) NOT NULL,
    `kind` INT NOT NULL,
    `prefix` VARCHAR(400) NOT NULL,
    `suffix_pattern` VARCHAR(200),
    `depth` SMALLINT NOT NULL DEFAULT 0,
    `ext` VARCHAR(32),
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `idx_claim_path_scan` (`project_uuid`, `status`, `prefix`, `expires_at`),
    INDEX `idx_claim_path_claim` (`claim_uuid`),
    INDEX `idx_claim_path_session` (`session_uuid`, `status`),
    CONSTRAINT `claim_has_paths`
        FOREIGN KEY (`claim_uuid`)
        REFERENCES `claim` (`id`)
        ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `intent_token` (
    `id` CHAR(36) NOT NULL,
    `intent_uuid` CHAR(36) NOT NULL,
    `team_uuid` CHAR(36) NOT NULL,
    `project_uuid` CHAR(36) NOT NULL,
    `token` VARCHAR(32) NOT NULL,
    `weight` SMALLINT NOT NULL DEFAULT 1,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `idx_intent_token_lookup` (`project_uuid`, `token`),
    CONSTRAINT `intent_has_tokens`
        FOREIGN KEY (`intent_uuid`)
        REFERENCES `intent` (`id`)
        ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `contract_assertion` (
    `id` CHAR(36) NOT NULL,
    `contract_uuid` CHAR(36) NOT NULL,
    `team_uuid` CHAR(36) NOT NULL,
    `project_uuid` CHAR(36) NOT NULL,
    `session_uuid` CHAR(36) NOT NULL,
    `member_uuid` CHAR(36) NOT NULL,
    `role` INT NOT NULL,
    `shape` JSON,
    `shape_hash` VARCHAR(64) NOT NULL,
    `shape_fingerprint` VARCHAR(64) NOT NULL,
    `status` INT NOT NULL,
    `revision` INT NOT NULL DEFAULT 1,
    `active_marker` SMALLINT,
    `asserted_at` DATETIME,
    `superseded_by_uuid` CHAR(36),
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `idx_contract_assertion_role` (`contract_uuid`, `status`, `role`),
    UNIQUE INDEX `uq_contract_assertion_active` (`contract_uuid`, `session_uuid`, `role`, `active_marker`),
    CONSTRAINT `contract_has_assertions`
        FOREIGN KEY (`contract_uuid`)
        REFERENCES `contract` (`id`)
        ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `contract_field` (
    `id` CHAR(36) NOT NULL,
    `assertion_uuid` CHAR(36) NOT NULL,
    `contract_uuid` CHAR(36) NOT NULL,
    `path` VARCHAR(255) NOT NULL,
    `path_snake` VARCHAR(255) NOT NULL,
    `type` INT NOT NULL,
    `required` TINYINT(1) NOT NULL DEFAULT 0,
    `nullable` TINYINT(1) NOT NULL DEFAULT 0,
    `direction` INT NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `idx_contract_field_antijoin` (`contract_uuid`, `path`, `direction`),
    INDEX `idx_contract_field_snake` (`contract_uuid`, `path_snake`),
    UNIQUE INDEX `uq_contract_field_path` (`assertion_uuid`, `path`),
    CONSTRAINT `assertion_has_fields`
        FOREIGN KEY (`assertion_uuid`)
        REFERENCES `contract_assertion` (`id`)
        ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `conflict` (
    `id` CHAR(36) NOT NULL,
    `team_uuid` CHAR(36) NOT NULL,
    `project_uuid` CHAR(36) NOT NULL,
    `key` VARCHAR(32) NOT NULL,
    `kind` INT NOT NULL,
    `dedupe_key` VARCHAR(64) NOT NULL,
    `severity` INT NOT NULL,
    `status` INT NOT NULL,
    `detected_by` INT NOT NULL,
    `detector_rule` VARCHAR(48),
    `confidence` DECIMAL(38,2),
    `evidence` JSON,
    `suggested_action` VARCHAR(400),
    `suggested_yield_session_uuid` CHAR(36),
    `suggested_yield_reason` VARCHAR(80),
    `resolution` INT,
    `resolution_note` VARCHAR(400),
    `dismiss_reason` INT,
    `resolved_by_member_uuid` CHAR(36),
    `resolved_at` DATETIME,
    `occurrence_count` INT NOT NULL DEFAULT 1,
    `first_detected_at` DATETIME,
    `last_detected_at` DATETIME,
    `notified_at` DATETIME,
    `max_severity_notified` INT,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `idx_conflict_open` (`team_uuid`, `status`, `severity`),
    UNIQUE INDEX `uq_conflict_dedupe` (`team_uuid`, `dedupe_key`),
    UNIQUE INDEX `uq_conflict_team_key` (`team_uuid`, `key`),
    CONSTRAINT `team_has_conflicts`
        FOREIGN KEY (`team_uuid`)
        REFERENCES `team` (`id`)
        ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `conflict_participant` (
    `id` CHAR(36) NOT NULL,
    `conflict_uuid` CHAR(36) NOT NULL,
    `team_uuid` CHAR(36) NOT NULL,
    `session_uuid` CHAR(36) NOT NULL,
    `agent_uuid` CHAR(36) NOT NULL,
    `member_uuid` CHAR(36) NOT NULL,
    `subject_kind` INT NOT NULL,
    `subject_uuid` CHAR(36) NOT NULL,
    `role` INT NOT NULL,
    `notified_at` DATETIME,
    `acked_at` DATETIME,
    `response` INT,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `idx_participant_session` (`session_uuid`, `conflict_uuid`),
    CONSTRAINT `conflict_has_participants`
        FOREIGN KEY (`conflict_uuid`)
        REFERENCES `conflict` (`id`)
        ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `judgement` (
    `id` CHAR(36) NOT NULL,
    `team_uuid` CHAR(36) NOT NULL,
    `pair_key` VARCHAR(64) NOT NULL,
    `kind` INT NOT NULL,
    `subject_a_kind` INT NOT NULL,
    `subject_a_uuid` CHAR(36) NOT NULL,
    `subject_a_revision` INT NOT NULL DEFAULT 1,
    `subject_b_kind` INT NOT NULL,
    `subject_b_uuid` CHAR(36) NOT NULL,
    `subject_b_revision` INT NOT NULL DEFAULT 1,
    `status` INT NOT NULL,
    `verdict` INT,
    `severity` INT,
    `confidence` DECIMAL(38,2),
    `rationale` VARCHAR(400),
    `judge_session_uuid` CHAR(36),
    `judging_expires_at` DATETIME,
    `conflict_uuid` CHAR(36),
    `pinned` TINYINT(1) NOT NULL DEFAULT 0,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `idx_judgement_assignment` (`judge_session_uuid`, `status`, `judging_expires_at`),
    UNIQUE INDEX `uq_judgement_pair` (`team_uuid`, `pair_key`),
    CONSTRAINT `team_has_judgements`
        FOREIGN KEY (`team_uuid`)
        REFERENCES `team` (`id`)
        ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `instruction` (
    `id` CHAR(36) NOT NULL,
    `team_uuid` CHAR(36) NOT NULL,
    `target_session_uuid` CHAR(36),
    `target_agent_uuid` CHAR(36),
    `key` VARCHAR(32) NOT NULL,
    `source` INT NOT NULL,
    `kind` INT NOT NULL,
    `body` VARCHAR(600) NOT NULL,
    `ref_kind` INT,
    `ref_uuid` CHAR(36),
    `requires_report` TINYINT(1) NOT NULL DEFAULT 0,
    `status` INT NOT NULL,
    `raised_by_member_uuid` CHAR(36),
    `delivered_at` DATETIME,
    `acted_at` DATETIME,
    `action` INT,
    `action_note` VARCHAR(400),
    `expires_at` DATETIME,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `idx_instruction_pending` (`target_session_uuid`, `status`),
    UNIQUE INDEX `uq_instruction_team_key` (`team_uuid`, `key`),
    CONSTRAINT `team_has_instructions`
        FOREIGN KEY (`team_uuid`)
        REFERENCES `team` (`id`)
        ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `team_event` (
    `id` CHAR(36) NOT NULL,
    `team_uuid` CHAR(36) NOT NULL,
    `sequence` BIGINT NOT NULL,
    `project_uuid` CHAR(36),
    `session_uuid` CHAR(36),
    `agent_uuid` CHAR(36),
    `member_uuid` CHAR(36),
    `kind` INT NOT NULL,
    `subject_kind` INT,
    `subject_uuid` CHAR(36),
    `subject_key` VARCHAR(64),
    `structural` TINYINT(1) NOT NULL DEFAULT 0,
    `summary` VARCHAR(240),
    `payload` JSON,
    `idempotency_key` VARCHAR(255) NOT NULL,
    `response_snapshot` JSON,
    `occurred_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `idx_team_event_session` (`session_uuid`, `sequence`),
    UNIQUE INDEX `uq_team_event_sequence` (`team_uuid`, `sequence`),
    UNIQUE INDEX `uq_team_event_idempotency` (`team_uuid`, `idempotency_key`),
    CONSTRAINT `team_has_events`
        FOREIGN KEY (`team_uuid`)
        REFERENCES `team` (`id`)
        ON DELETE CASCADE
) ENGINE = InnoDB;

