// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/mklfarha/metiche/backend/entity/notification_channel"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchNotificationChannelByIDRequest struct {
	ID uuid.UUID
}

func (r FetchNotificationChannelByIDRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("id", r.ID.String())

	return nil
}

type FetchNotificationChannelByIDResponse struct {
	Results []main_entity.NotificationChannel
}
