-- Code generated by nuzur go-code-gen. DO NOT EDIT.
-- name: InsertPlan :execresult
INSERT INTO `plan`
(`id`,`key`,`name`,`description`,`max_concurrent_agents`,`retention_days`,`max_members`,`max_projects`,`is_instance_default`,`sort_order`,`status`,`created_at`,`updated_at`)
VALUES
(?,?,?,?,?,?,?,?,?,?,?,?,?);

-- name: InsertAccount :execresult
INSERT INTO `account`
(`id`,`key`,`display_name`,`token_hash`,`identity_provider`,`identity_subject`,`identity_handle`,`email`,`claimed_at`,`status`,`last_seen_at`,`created_at`,`updated_at`)
VALUES
(?,?,?,?,?,?,?,?,?,?,?,?,?);

-- name: InsertTeam :execresult
INSERT INTO `team`
(`id`,`name`,`slug`,`sequence`,`board_revision`,`settings`,`status`,`created_at`,`updated_at`,`plan_uuid`,`plan_source`,`plan_granted_reason`,`plan_expires_at`,`retention_floor_sequence`,`last_retention_sweep_at`,`visibility`,`requires_claimed_accounts`)
VALUES
(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);

-- name: InsertAgent :execresult
INSERT INTO `agent`
(`id`,`key`,`label`,`client_kind`,`client_key`,`status`,`last_seen_at`,`created_at`,`updated_at`,`account_uuid`,`token_hash`)
VALUES
(?,?,?,?,?,?,?,?,?,?,?);

-- name: InsertMember :execresult
INSERT INTO `member`
(`id`,`team_uuid`,`key`,`display_name`,`role`,`last_seen_at`,`status`,`created_at`,`updated_at`,`account_uuid`,`revoked_at`)
VALUES
(?,?,?,?,?,?,?,?,?,?,?);

-- name: InsertProject :execresult
INSERT INTO `project`
(`id`,`team_uuid`,`key`,`name`,`repo_url`,`default_branch`,`ignore_patterns`,`hotspot_patterns`,`case_insensitive_paths`,`status`,`created_at`,`updated_at`,`cadence`)
VALUES
(?,?,?,?,?,?,?,?,?,?,?,?,?);

-- name: InsertInvite :execresult
INSERT INTO `invite`
(`id`,`team_uuid`,`code`,`label`,`created_by_member_uuid`,`max_uses`,`uses`,`expires_at`,`revoked_at`,`revoked_by_member_uuid`,`status`,`last_used_at`,`created_at`,`updated_at`)
VALUES
(?,?,?,?,?,?,?,?,?,?,?,?,?,?);

-- name: InsertContract :execresult
INSERT INTO `contract`
(`id`,`team_uuid`,`project_uuid`,`key`,`key_norm`,`kind`,`status`,`title`,`notes`,`created_at`,`updated_at`)
VALUES
(?,?,?,?,?,?,?,?,?,?,?);

-- name: InsertDecision :execresult
INSERT INTO `decision`
(`id`,`team_uuid`,`project_uuid`,`key`,`title`,`statement`,`rationale`,`status`,`always_show`,`supersedes_uuid`,`superseded_by_uuid`,`decided_by_member_uuid`,`decided_at`,`revision`,`created_at`,`updated_at`)
VALUES
(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);

-- name: InsertNotificationChannel :execresult
INSERT INTO `notification_channel`
(`id`,`team_uuid`,`project_uuid`,`key`,`kind`,`label`,`target_url`,`min_severity`,`notify_human_requests`,`status`,`delivery_status`,`consecutive_failures`,`last_attempt_at`,`last_success_at`,`last_error`,`created_by_member_uuid`,`created_at`,`updated_at`)
VALUES
(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);

-- name: InsertDecisionPath :execresult
INSERT INTO `decision_path`
(`id`,`decision_uuid`,`team_uuid`,`project_uuid`,`pattern`,`pattern_norm`,`kind`,`prefix`,`depth`,`created_at`,`updated_at`)
VALUES
(?,?,?,?,?,?,?,?,?,?,?);

-- name: InsertDecisionToken :execresult
INSERT INTO `decision_token`
(`id`,`decision_uuid`,`team_uuid`,`project_uuid`,`token`,`weight`,`created_at`,`updated_at`)
VALUES
(?,?,?,?,?,?,?,?);

-- name: InsertSession :execresult
INSERT INTO `session`
(`id`,`team_uuid`,`project_uuid`,`agent_uuid`,`member_uuid`,`key`,`branch`,`base_commit`,`head_commit`,`goal`,`status`,`status_line`,`current_intent_uuid`,`started_at`,`last_heartbeat_at`,`ended_at`,`outcome`,`outcome_note`,`created_at`,`updated_at`)
VALUES
(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);

-- name: InsertIntent :execresult
INSERT INTO `intent`
(`id`,`team_uuid`,`project_uuid`,`session_uuid`,`member_uuid`,`key`,`summary`,`detail`,`kind`,`status`,`external_ref`,`revision`,`declared_at`,`started_at`,`ended_at`,`expires_at`,`created_at`,`updated_at`)
VALUES
(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);

-- name: InsertClaim :execresult
INSERT INTO `claim`
(`id`,`team_uuid`,`project_uuid`,`session_uuid`,`member_uuid`,`intent_uuid`,`key`,`mode`,`status`,`ttl_seconds`,`expires_at`,`hard_expires_at`,`breadth_score`,`released_at`,`release_reason`,`created_at`,`updated_at`)
VALUES
(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);

-- name: InsertClaimPath :execresult
INSERT INTO `claim_path`
(`id`,`claim_uuid`,`project_uuid`,`session_uuid`,`member_uuid`,`mode`,`status`,`expires_at`,`pattern`,`pattern_norm`,`kind`,`prefix`,`suffix_pattern`,`depth`,`ext`,`created_at`,`updated_at`)
VALUES
(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);

-- name: InsertIntentToken :execresult
INSERT INTO `intent_token`
(`id`,`intent_uuid`,`team_uuid`,`project_uuid`,`token`,`weight`,`created_at`,`updated_at`)
VALUES
(?,?,?,?,?,?,?,?);

-- name: InsertContractAssertion :execresult
INSERT INTO `contract_assertion`
(`id`,`contract_uuid`,`team_uuid`,`project_uuid`,`session_uuid`,`member_uuid`,`role`,`shape`,`shape_hash`,`shape_fingerprint`,`status`,`revision`,`active_marker`,`asserted_at`,`superseded_by_uuid`,`created_at`,`updated_at`)
VALUES
(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);

-- name: InsertContractField :execresult
INSERT INTO `contract_field`
(`id`,`assertion_uuid`,`contract_uuid`,`path`,`path_snake`,`type`,`required`,`nullable`,`direction`,`created_at`,`updated_at`)
VALUES
(?,?,?,?,?,?,?,?,?,?,?);

-- name: InsertConflict :execresult
INSERT INTO `conflict`
(`id`,`team_uuid`,`project_uuid`,`key`,`kind`,`dedupe_key`,`severity`,`status`,`detected_by`,`detector_rule`,`confidence`,`evidence`,`suggested_action`,`suggested_yield_session_uuid`,`suggested_yield_reason`,`resolution`,`resolution_note`,`dismiss_reason`,`resolved_by_member_uuid`,`resolved_at`,`occurrence_count`,`first_detected_at`,`last_detected_at`,`notified_at`,`max_severity_notified`,`created_at`,`updated_at`)
VALUES
(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);

-- name: InsertConflictParticipant :execresult
INSERT INTO `conflict_participant`
(`id`,`conflict_uuid`,`team_uuid`,`session_uuid`,`agent_uuid`,`member_uuid`,`subject_kind`,`subject_uuid`,`role`,`notified_at`,`acked_at`,`response`,`created_at`,`updated_at`)
VALUES
(?,?,?,?,?,?,?,?,?,?,?,?,?,?);

-- name: InsertJudgement :execresult
INSERT INTO `judgement`
(`id`,`team_uuid`,`pair_key`,`kind`,`subject_a_kind`,`subject_a_uuid`,`subject_a_revision`,`subject_b_kind`,`subject_b_uuid`,`subject_b_revision`,`status`,`verdict`,`severity`,`confidence`,`rationale`,`judge_session_uuid`,`judging_expires_at`,`conflict_uuid`,`pinned`,`created_at`,`updated_at`)
VALUES
(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);

-- name: InsertInstruction :execresult
INSERT INTO `instruction`
(`id`,`team_uuid`,`target_session_uuid`,`target_agent_uuid`,`key`,`source`,`kind`,`body`,`ref_kind`,`ref_uuid`,`requires_report`,`status`,`raised_by_member_uuid`,`delivered_at`,`acted_at`,`action`,`action_note`,`expires_at`,`created_at`,`updated_at`,`target_member_uuid`)
VALUES
(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);

-- name: InsertTeamEvent :execresult
INSERT INTO `team_event`
(`id`,`team_uuid`,`sequence`,`project_uuid`,`session_uuid`,`agent_uuid`,`member_uuid`,`kind`,`subject_kind`,`subject_uuid`,`subject_key`,`structural`,`summary`,`payload`,`idempotency_key`,`response_snapshot`,`occurred_at`,`created_at`,`updated_at`)
VALUES
(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);

-- name: InsertLimitEvent :execresult
INSERT INTO `limit_event`
(`id`,`team_uuid`,`plan_uuid`,`session_uuid`,`dimension`,`observed`,`allowed`,`outcome`,`note`,`occurred_at`,`created_at`,`updated_at`)
VALUES
(?,?,?,?,?,?,?,?,?,?,?,?);

