// Code generated by nuzur go-code-gen. DO NOT EDIT.

package decision_token

import (
	entitytypes "github.com/mklfarha/metiche/backend/entity/types"
)

func (e DecisionToken) FieldIdentifierToTypeMap() map[string]entitytypes.FieldType {
	return map[string]entitytypes.FieldType{
		"id":            entitytypes.StringFieldType,
		"decision_uuid": entitytypes.StringFieldType,
		"team_uuid":     entitytypes.StringFieldType,
		"project_uuid":  entitytypes.StringFieldType,
		"token":         entitytypes.StringFieldType,
		"weight":        entitytypes.IntFieldType,
		"created_at":    entitytypes.TimestampFieldType,
		"updated_at":    entitytypes.TimestampFieldType,
	}
}

func (e DecisionToken) OrderedFieldIdentifiers() []string {
	res := []string{}
	res = append(res, "id")
	res = append(res, "decision_uuid")
	res = append(res, "team_uuid")
	res = append(res, "project_uuid")
	res = append(res, "token")
	res = append(res, "weight")
	res = append(res, "created_at")
	res = append(res, "updated_at")

	return res
}

func (e DecisionToken) DependantFieldIdentifierToTypeMap() map[string]map[string]entitytypes.FieldType {
	res := make(map[string]map[string]entitytypes.FieldType)

	return res
}

func (e DecisionToken) EntityIdentifier() string {
	return "decision_token"
}

func (e DecisionToken) PrimaryKeyIdentifiers() []string {
	return []string{
		"id",
	}
}

func (e DecisionToken) ArrayFieldIdentifierToType() map[string]entitytypes.FieldType {
	res := make(map[string]entitytypes.FieldType)

	return res
}
