// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/mklfarha/metiche/backend/entity/claim_path"

	"github.com/gofrs/uuid"
	"github.com/mklfarha/metiche/backend/enums"
	"go.uber.org/zap/zapcore"
)

type FetchClaimPathByProjectUUIDAndStatusAndPrefixRequest struct {
	ProjectUUID uuid.UUID
	Status      enums.ClaimStatus
	Prefix      string

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchClaimPathByProjectUUIDAndStatusAndPrefixRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("project_uuid", r.ProjectUUID.String())

	return nil
}

type FetchClaimPathByProjectUUIDAndStatusAndPrefixResponse struct {
	Results []main_entity.ClaimPath
}
