// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/mklfarha/metiche/backend/entity/claim_path"

	"github.com/gofrs/uuid"
)

type UpsertRequest struct {
	ClaimPath main_entity.ClaimPath
}

type UpsertResponse struct {
	ID uuid.UUID
}
