// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/mklfarha/metiche/backend/entity/judgement"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchJudgementByTeamUUIDAndSubjectAUUIDAndSubjectBUUIDRequest struct {
	TeamUUID     uuid.UUID
	SubjectAUUID uuid.UUID
	SubjectBUUID uuid.UUID

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchJudgementByTeamUUIDAndSubjectAUUIDAndSubjectBUUIDRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("team_uuid", r.TeamUUID.String())

	e.AddString("subject_a_uuid", r.SubjectAUUID.String())

	e.AddString("subject_b_uuid", r.SubjectBUUID.String())

	return nil
}

type FetchJudgementByTeamUUIDAndSubjectAUUIDAndSubjectBUUIDResponse struct {
	Results []main_entity.Judgement
}
