// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "github.com/mklfarha/metiche/backend/entity/judgement"

	"github.com/gofrs/uuid"
)

type UpsertRequest struct {
	Judgement main_entity.Judgement
}

type UpsertResponse struct {
	ID uuid.UUID
}
