// Code generated by nuzur go-code-gen. DO NOT EDIT.

package notification_channel

import (
	"context"

	"github.com/mklfarha/metiche/backend/core/module/notification_channel/types"
	metichedb "github.com/mklfarha/metiche/backend/core/repository/gen"

	"github.com/gofrs/uuid"

	"time"

	"github.com/mklfarha/metiche/backend/entity/mapper"
)

func (m *module) Insert(
	ctx context.Context,
	req types.UpsertRequest,
	opts ...Option,
) (types.UpsertResponse, error) {

	// auto-generate primary-key UUIDs for new records when not supplied by the caller
	if req.NotificationChannel.ID == uuid.Nil {
		req.NotificationChannel.ID = uuid.Must(uuid.NewV4())
	}

	// server-managed timestamps (generated created_at/updated_at)
	req.NotificationChannel.CreatedAt = time.Now()
	req.NotificationChannel.UpdatedAt = time.Now()

	// validate the new record against the schema's field type/type-config rules
	if err := req.NotificationChannel.Validate(); err != nil {

		return types.UpsertResponse{}, err
	}

	optConfig := applyAllOptions(opts)

	tx := optConfig.SQLTx
	createdTx := false
	if tx == nil {
		ntx, err := m.repository.DB.Begin()
		if err != nil {
			return types.UpsertResponse{}, err
		}
		tx = ntx
		defer tx.Rollback()
		createdTx = true
	}

	qtx := m.repository.Queries.WithTx(tx)
	params := mapUpsertRequestToInsertParams(req)

	_, err := qtx.InsertNotificationChannel(
		ctx,
		params,
	)
	if err != nil {

		return types.UpsertResponse{}, err
	}

	if createdTx {
		err := tx.Commit()
		if err != nil {

			return types.UpsertResponse{}, err
		}
	}

	// The rows this module caches have changed, so everything it holds is
	// suspect: drop it rather than answer a later read from a snapshot that
	// predates this write. The cache is per entity, so this discards only this
	// entity's reads. (It is a no-op while a caller-supplied transaction is
	// still open — those reads bypass the cache anyway.)
	m.cache.Flush()

	return buildInsertResponse(req), nil
}

func buildInsertResponse(req types.UpsertRequest) types.UpsertResponse {
	return types.UpsertResponse{

		ID: req.NotificationChannel.ID,
	}
}

func mapUpsertRequestToInsertParams(req types.UpsertRequest) metichedb.InsertNotificationChannelParams {
	return metichedb.InsertNotificationChannelParams{
		ID: req.NotificationChannel.ID.String(),

		TeamUUID: req.NotificationChannel.TeamUUID.String(),

		ProjectUUID: mapper.UUIDPtrToNullString(req.NotificationChannel.ProjectUUID),

		Key: req.NotificationChannel.Key,

		Kind: req.NotificationChannel.Kind.ToInt64(),

		Label: req.NotificationChannel.Label,

		TargetURL: req.NotificationChannel.TargetURL,

		MinSeverity: req.NotificationChannel.MinSeverity.ToInt64(),

		NotifyHumanRequests: req.NotificationChannel.NotifyHumanRequests,

		Status: req.NotificationChannel.Status.ToInt64(),

		DeliveryStatus: req.NotificationChannel.DeliveryStatus.ToInt64(),

		ConsecutiveFailures: req.NotificationChannel.ConsecutiveFailures,

		LastAttemptAt: req.NotificationChannel.LastAttemptAt,

		LastSuccessAt: req.NotificationChannel.LastSuccessAt,

		LastError: req.NotificationChannel.LastError,

		CreatedByMemberUUID: mapper.UUIDPtrToNullString(req.NotificationChannel.CreatedByMemberUUID),

		CreatedAt: req.NotificationChannel.CreatedAt,

		UpdatedAt: req.NotificationChannel.UpdatedAt,
	}
}
