// Code generated by nuzur go-code-gen. DO NOT EDIT.

package contract_assertion

import (
	"context"
	"fmt"

	"github.com/mklfarha/metiche/backend/core/module/contract_assertion/types"

	"errors"
	metichedb "github.com/mklfarha/metiche/backend/core/repository/gen"
)

func (m *module) FetchContractAssertionByContractUUIDAndSessionUUIDAndRoleAndActiveMarker(
	ctx context.Context,
	req types.FetchContractAssertionByContractUUIDAndSessionUUIDAndRoleAndActiveMarkerRequest,
	opts ...Option,
) (types.FetchContractAssertionByContractUUIDAndSessionUUIDAndRoleAndActiveMarkerResponse, error) {

	resolvedOpts := applyAllOptions(opts)
	queries := m.repository.Queries
	if resolvedOpts.SQLTx != nil {
		queries = queries.WithTx(resolvedOpts.SQLTx)
	}
	// A read inside a transaction must observe that transaction's own
	// uncommitted writes, so it can neither be served from the shared cache nor
	// be collapsed into another caller's in-flight query.
	skipShared := resolvedOpts.SkipCache || resolvedOpts.SQLTx != nil
	cacheKey := fmt.Sprintf("FetchContractAssertionByContractUUIDAndSessionUUIDAndRoleAndActiveMarker:%v", req)
	if !skipShared {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.FetchContractAssertionByContractUUIDAndSessionUUIDAndRoleAndActiveMarkerResponse), nil
		}
	}
	fetch := func() (any, error) {
		if req.OrderBy == "" {
			models, err := queries.FetchContractAssertionByContractUUIDAndSessionUUIDAndRoleAndActiveMarker(
				ctx,
				metichedb.FetchContractAssertionByContractUUIDAndSessionUUIDAndRoleAndActiveMarkerParams{
					ContractUUID: req.ContractUUID.String(),

					SessionUUID: req.SessionUUID.String(),

					Role: req.Role.ToInt64(),

					ActiveMarker: req.ActiveMarker,

					Offset: req.Offset,
					Limit:  req.Limit,
				},
			)

			if err != nil {

				return types.FetchContractAssertionByContractUUIDAndSessionUUIDAndRoleAndActiveMarkerResponse{}, err
			}
			return types.FetchContractAssertionByContractUUIDAndSessionUUIDAndRoleAndActiveMarkerResponse{
				Results: mapModelsToEntities(models),
			}, nil
		}

		err := errors.New("could not process request")

		return types.FetchContractAssertionByContractUUIDAndSessionUUIDAndRoleAndActiveMarkerResponse{}, err
	} // end fetch
	var v any
	var fetchErr error
	if skipShared {
		v, fetchErr = fetch()
	} else {
		v, fetchErr, _ = m.sg.Do(cacheKey, fetch)
	}
	if fetchErr != nil {
		return types.FetchContractAssertionByContractUUIDAndSessionUUIDAndRoleAndActiveMarkerResponse{}, fetchErr
	}
	result := v.(types.FetchContractAssertionByContractUUIDAndSessionUUIDAndRoleAndActiveMarkerResponse)
	if !skipShared {
		m.cache.Set(cacheKey, result, 0)
	}
	return result, nil

}
